### ISSUE TITLE
Destroy cluster leaves aws-auth configmap

### ISSUE THREAD

**Issue by mikehenry-bi** [terraform-aws-modules/terraform-aws-eks#1259] opened 2021-02-27 23:55 UTC
# Destroy cluster not destroying cleanly

I created a cluster using the latest version of this module with properly configured Kubernetes provider, conditional creation, single node-group, and module-managed `aws-auth` configmap, but when destroying the cluster we get the following error:
```
module.cluster.kubernetes_config_map.aws_auth[0]: Destroying... [id=kube-system/aws-auth]
Error: Unauthorized
```
At this point the cluster is deleted but a `kubernetes_config_map` with name `aws_auth` remains in the state.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

On destroy the cluster gets removed, but not the `aws-auth` config map, causing the `terraform destroy` command to fail with the above error(s). Looking at the remaining Terraform state, I can see that a `kubernetes_config_map` with name `aws_auth` remains.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. Create a cluster with this module using `terraform plan` and `apply`.
2. Destroy the cluster using `terraform destroy`.

## What's the expected behavior?

The expected behavior is that the cluster gets removed cleanly, without errors or left-overs in the state.

## Are you able to fix this problem and submit a PR? Link here if you have already.

A work-around can be achieved by using the `terraform state rm` command:

```
terraform state rm 'module.cluster.kubernetes_config_map.aws_auth'
terraform destroy -auto-approve
```

## Environment details

* Affected module version: 14.0.0
* OS: Linux
* Terraform version: v0.14.7

## Any other relevant info

Kubernetes provider (v2.0.2) is configured like in the example for conditional creation:

```
data "aws_eks_cluster" "cluster" {
  count = var.enable ? 1 : 0
  name  = module.cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  count = var.enable ? 1 : 0
  name  = module.cluster.cluster_id
}

provider "kubernetes" {
  host                   = coalescelist(data.aws_eks_cluster.cluster[*].endpoint, [""])[0]
  cluster_ca_certificate = coalescelist(data.aws_eks_cluster.cluster[*].certificate_authority.0.data, [""])[0]
  token                  = coalescelist(data.aws_eks_cluster_auth.cluster[*].token, [""])[0]
}

module "cluster" {
  create_eks = var.enable
  source     = "terraform-aws-modules/eks/aws"

  cluster_name    = var.cluster_name
  cluster_version = var.kubernetes_version
  subnets         = var.subnets
  vpc_id          = var.vpc_id

  cluster_endpoint_private_access      = true
  cluster_endpoint_public_access       = true
  cluster_endpoint_public_access_cidrs = var.cluster_endpoint_public_access_cidrs

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 30
  }

  node_groups = {
    ng-a = {
      desired_capacity = 4
      max_capacity     = 5
      min_capacity     = 2

      instance_types = ["m5.large"]

      k8s_labels = {
        Environment = var.environment
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
      additional_tags = {
        ExtraTag = "example"
      }
    }
  }
```

**Comment by andrewbeard** [comment] 2021-03-11 19:13
This looks like a dupe of #1162.

**Comment by mikehenry-bi** [comment] 2021-03-11 19:17
Yes, it does.. Feel free to close this out.

**Comment by barryib** [comment] 2021-05-19 09:05
Closing since it duplicates https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1282.

Feel free to re-open it if needed.

**Closed by barryib** 2021-05-19 09:05 UTC

**Comment by ddvdozuki** [comment] 2021-09-05 17:54
I'm having this same issue but I'm not using conditional creation. It happens intermittently where the config map will be left behind and cause the same failure: 

```
data "aws_eks_cluster" "main" {
  name = module.eks_cluster.cluster_id
}
data "aws_eks_cluster_auth" "main" {
  name = module.eks_cluster.cluster_id
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.main.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.main.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.main.token
}
module "eks_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.11.0"

  depends_on = [aws_iam_policy.cluster_access, aws_iam_policy.eks_worker]

  # EKS cofigurations
  cluster_name    = local.identifier
  cluster_version = "1.20"
  enable_irsa     = true

  vpc_id  = var.vpc_id
  subnets = data.aws_subnets.private.ids

  workers_role_name = "${local.identifier}-${data.aws_region.current.name}-worker"

  workers_additional_policies = [
    aws_iam_policy.eks_worker.arn,
  ]

  node_groups_defaults = {
    instance_types = [var.eks_instance_type]
    disk_size      = var.eks_volume_size
  }

  node_groups = {
    workers = {
      desired_capacity = var.eks_desired_capacity
      max_capacity     = var.eks_max_size
      min_capacity     = var.eks_min_size
      capacity_type  = "SPOT"

      k8s_labels = {
        Environment = var.environment
      }

      additional_tags = {
        Environment = var.environment
      }
    }
  }

  # Kubernetes configurations
  write_kubeconfig = false

  map_roles = [ # aws-auth configmap
    {
      rolearn  = module.cluster_access_role.this_iam_role_arn
      username = "admin"
      groups   = ["system:masters"]
    },
  ]

  tags = local.tags
}
```
