### ISSUE TITLE
Getting  x509: certificate signed by unknown authority while creating eks cluster.

### ISSUE THREAD

**Issue by ahilmathew** [terraform-aws-modules/terraform-aws-eks#1425] opened 2021-06-03 04:28 UTC
## Description

I'm trying to collect more information and possibly find out what I'm doing wrong here. I've been getting a `certificate signed by unknown authority` error from the `http.wait_for_cluster` data source while trying to create an EKS cluster.
```
│ Error: Error making request: Get "https://<cluster_endpoint>/healthz": x509: certificate signed by unknown authority
│ 
│   with module.eks.data.http.wait_for_cluster[0],
│   on external-modules/terraform-aws-eks/cluster.tf line 68, in data "http" "wait_for_cluster":
│   68: data "http" "wait_for_cluster" {

```

This is how my code looks like.
```
module "eks" {
  source     = "./external-modules/terraform-aws-eks"
  depends_on = [data.aws_vpc_endpoint.sts, aws_vpc_endpoint.s3, aws_vpc_endpoint.logs, aws_vpc_endpoint.ecr_dkr, aws_vpc_endpoint.ecr_api, aws_vpc_endpoint.ec2, aws_route53_resolver_rule_association.test]
  cluster_name                    = local.cluster_name
  cluster_version                 = var.cluster_version
  subnets                         = var.subnets
  vpc_id                          = var.vpc_id
  cluster_endpoint_private_access = true
  #To be removed after fixing EKS local access
  cluster_endpoint_public_access = true
  node_groups = {
    example = {
      desired_capacity = var.desired_capacity
      max_capacity     = var.max_capacity
      min_capacity     = var.min_capacity

      launch_template_id      = aws_launch_template.default.id
      launch_template_version = aws_launch_template.default.default_version

      additional_tags = var.additional_tags
    }
  }
}
```
## Versions

 - Terraform:  0.15
 - Provider(s):
```
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

```

 - Module:

## Reproduction

I've been using a local copy of this module and using it to create a private EKS cluster. The terraform code is run from a CI tool and this runs behind a corporate proxy.

## Expected behavior

EKS Cluster gets created and worked nodes join the cluster.
## Actual behavior

Fails to create EKS cluster.

**Comment by barryib** [comment] 2021-06-03 06:44
Normally, the http provider follows proxy specifications.

Did you set http_proxy/https_proxy environment variables ?

**Comment by ahilmathew** [comment] 2021-06-03 07:11
Yes, Those are set as part of the jenkins step.
```
steps {
        script {
          withEnv([
            "http_proxy=http://<proxy>:80",
            "https_proxy=http://<proxy>:80",
            "no_proxy=localhost,127.0.0.1,169.254.169.254",
            "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}",
            "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}",
            "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}",
          ])
```

**Comment by ahilmathew** [comment] 2021-06-03 08:31
https://github.com/terraform-aws-modules/terraform-provider-http/blob/main/internal/provider/data_source.go#L116

**Comment by barryib** [comment] 2021-06-03 09:11
Humm, just did some tests from our private network where we can go through internet without using our corporate proxy.

## My configuration

```hcl
terraform {
  required_providers {
    http = {
      source = "terraform-aws-modules/http"
    }
  }
}

data "http" "example" {
  url = "https://httpstat.us/200"

  request_headers = {
    Accept = "application/json"
  }
}

output "example" {
  value = data.http.example.body
}
```

## Test without proxy

```shell
➜  tf-tests env | grep proxy
➜  tf-tests tf apply        

Error: Error making request: Get "https://httpstat.us/200": dial tcp: lookup httpstat.us on 172.31.55.30:53: no such host

  on test.tf line 14, in data "http" "example":
  14: data "http" "example" {
```

## Test with proxy (in CAPITAL and in lowercase)

```shell
➜  tf-tests env | grep proxy
http_proxy=http://<proxy>:8080/
https_proxy=http://<proxy>:8080/
HTTP_PROXY=http://<proxy>:8080/
HTTPS_PROXY=http://<proxy>:8080/
➜  tf-tests tf apply        

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = "{\"code\": 200, \"description\": \"OK\"}"
➜  tf-tests unset HTTPS_PROXY
➜  tf-tests unset HTTP_PROXY 
➜  tf-tests tf apply         

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = "{\"code\": 200, \"description\": \"OK\"}"
➜  tf-tests prx
➜  tf-tests unset http_proxy
➜  tf-tests unset https_proxy
➜  tf-tests tf apply         

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = "{\"code\": 200, \"description\": \"OK\"}"
```

Also did the same tests on a private EKS endpoint with custom CA, and everything is working as expected.

Do you have this problem with curl ?
Is this happens once or every run ? 
What is your module version ? I've noticed that you're using a local version `"./external-modules/terraform-aws-eks"`.
Is this work without your `depends_on` in the module section ? Just wondering if this is not a bug in dependencies in TF 0.15. Can you please upgrade to latest version of Terraform 0.15 ?

**Comment by barryib** [comment] 2021-06-03 09:12
> https://github.com/terraform-aws-modules/terraform-provider-http/blob/main/internal/provider/data_source.go#L116

What you want me to see ?

**Comment by ahilmathew** [comment] 2021-06-03 09:52
Thank you for checking this out. I should've mentioned that I'm using this http module
https://github.com/terraform-aws-modules/terraform-provider-http

**Comment by ahilmathew** [comment] 2021-06-03 09:57
Do you have this problem with curl ? Nope. Curl returns 200.
Is this happens once or every run ? Yes
What is your module version ? I've noticed that you're using a local version "./external-modules/terraform-aws-eks". - I need to check. I'll upgrade to the latest version and check. 
The terraform-aws-modules/http provider version is 2.4.1.

Is this work without your depends_on in the module section ? Just wondering if this is not a bug in dependencies in TF 0.15. Can you please upgrade to latest version of Terraform 0.15 ? I'm using 0.15.4 now.

**Comment by barryib** [comment] 2021-06-03 10:13
> Do you have this problem with curl ? Nope. Curl returns 200.

Did you just `skip` TLS validation with curl or you used the CA provided by the EKS cluster ?

> Is this work without your depends_on in the module section ? Just wondering if this is not a bug in dependencies in TF 0.15. Can you please upgrade to latest version of Terraform 0.15 ? I'm using 0.15.4 now.

I'll say, it worth for testing only, to remove your `depends_on`.

Is this simple configuration work for you ?

```hcl
terraform {
  required_providers {
    http = {
      source = "terraform-aws-modules/http"
    }
  }
}

data "http" "example" {
  url = "https://<your-endpoint>/healthz"

  ca_certificate = base64decode("you-base64-encoded-CA-from-AWS-console")
}

output "example" {
  value = data.http.example.body
}
```

**Comment by ahilmathew** [comment] 2021-06-03 10:20
Just an update on the earlier comment, I updated to the latest version of the terraform-aws-eks module. This is part where it errors out - 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L89-L100
```
data "http" "wait_for_cluster" {
  count          = var.create_eks && var.manage_aws_auth ? 1 : 0
  url            = format("%s/healthz", aws_eks_cluster.this[0].endpoint)
  ca_certificate = base64decode(coalescelist(aws_eks_cluster.this[*].certificate_authority[0].data, [""])[0])
  timeout        = var.wait_for_cluster_timeout

  depends_on = [
    aws_eks_cluster.this,
    aws_security_group_rule.cluster_private_access_sg_source,
    aws_security_group_rule.cluster_private_access_cidrs_source,
  ]
}
```

**Comment by ahilmathew** [comment] 2021-06-03 10:23
>I'll say, it worth for testing only, to remove your depends_on.

Testing without `depends_on` now.

**Comment by ahilmathew** [comment] 2021-06-03 10:38
This is configuration I'm using now. Still fails. 
```
data "http" "wait_for_cluster" {
  url            = "https://ABCDEFGHIJN789065.gr7.ap-southeast-2.eks.amazonaws.com/healthz"
  ca_certificate = base64decode("base64-encoded-CA-from-AWS-console")
}
```

Also a correction on my earlier statement, `curl` doesn't work. The 200 I got was from the proxy.
```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ABCDEFGHIJN789065.gr7.ap-southeast-2.eks.amazonaws.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ABCDEFGHIJN789065.gr7.ap-southeast-2.eks.amazonaws.com:443 
```

**Comment by ahilmathew** [comment] 2021-06-04 00:54
I tried setting the `insecure` flag for the `http` provider to `true`. I got a 503 now.
```
│ Error: HTTP request error. Response code: 503
│ 
│   with module.eks_cluster.module.eks-cluster.data.http.wait_for_cluster[0],
│   on external-modules/terraform-aws-eks/data.tf line 89, in data "http" "wait_for_cluster":
│   89: data "http" "wait_for_cluster" {
│ 
```

**Comment by barryib** [comment] 2021-06-04 05:36
Please see with admins why your proxy is returning that error. See your proxy logs.

**Comment by ahilmathew** [comment] 2021-06-04 07:46
Thanks @barryib

**Comment by paper2** [comment] 2021-07-06 05:38
I have faced same problem. I solved it by adding ap-southeast-2.eks.amazonaws.com to "no_proxy".

**Comment by daroga0002** [comment] 2021-09-14 13:08
this is related to your proxy or  corporate setup which we cannot help here beside what was already posted. Closing this issue

**Closed by daroga0002** 2021-09-14 13:08 UTC
Labels: needs update

**Comment by arield-wix** [comment] 2022-05-03 14:31
atlantis plan
