### ISSUE TITLE
ignore_changes warning with Terraform v1.2.0

### ISSUE THREAD

**Issue by mikemurray86** [terraform-aws-modules/terraform-aws-eks#2081] opened 2022-05-19 19:41 UTC
## Description

When a plan or an apply is perfomred with terraform version 1.2.0 a warning is presented about a redundant ignore_changes element.  Any example from the `examples/*` can be used to reproduce the error message with the correct version of terraform.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.21.0 & 18.20.5

- Terraform & Provider versions:
      Terraform v1.2.0
      on darwin_amd64
      + provider registry.terraform.io/hashicorp/aws v4.12.1
      + provider registry.terraform.io/hashicorp/cloudinit v2.2.0
      + provider registry.terraform.io/hashicorp/helm v2.5.1
      + provider registry.terraform.io/hashicorp/kubernetes v2.11.0
      + provider registry.terraform.io/hashicorp/tls v3.3.0

## Reproduction Code [Required]

Any code in the examples will exibit this behavior. 

initialize and plan any configuration using this module.

## Expected behavior

a plan/apply that does not present a warning message

## Actual behavior

while all actions are still successful a warning message is presented about a `Redundant ignore_changes element`

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/547513/169389162-a179e058-2a42-467f-8acb-f34114cfda9b.png)

## Additional context

the changelog for terraform 1.2.0 mentions this new warning message will be presented going forward.

**Comment by bryantbiggs** [comment] 2022-05-21 17:40
We will have to investigate this further

**Comment by sanarena** [comment] 2022-05-30 06:43
Is this a tricky one? removing modifed_at from ignore_changes is not enough?

**Comment by antonbabenko** [comment] 2022-05-30 07:24
@sanarena Unfortunately, it is not enough because it will be different behavior for users using previous versions of Terraform (<1.2).

The problem is that currently, we don't know how to make the same code work for both Terraform ranges: `>= 1.2` and `< 1.2`.

**Comment by sklirg** [comment] 2022-05-30 07:32
Terraform output (v1.2.1) claims that the statement has no effect, though, or is that incorrect?

> │ Warning: Redundant ignore_changes element
│
│   on .terraform/modules/eks.eks/main.tf line 305, in resource "aws_eks_addon" "this":
│  305: resource "aws_eks_addon" "this" {
│
│ Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has
│ been created, retaining the value originally configured.
│
│ The attribute modified_at is decided by the provider alone and therefore there can be no configured value to compare with. **Including this
│ attribute in ignore_changes has no effect**. Remove the attribute from ignore_changes to quiet this warning.

**Comment by bryantbiggs** [comment] 2022-06-02 13:41
We will incorporate this change in v19.x

**Comment by ShonL** [comment] 2022-06-09 11:16
@bryantbiggs is it meaning that 19.x will require Terraform version to be 1.2 and above?

**Comment by kuboraam** [comment] 2022-06-12 18:38
@bryantbiggs is there a way to check terraform version in the code and modify the ignore_changes this only if version >=1.2 or is that too dirty? this can be done temporarily i guess, until eventually everyone upgrades to 1.3 and we can apply a permanent "fix" in future releases of the module.

**Comment by bryantbiggs** [comment] 2022-06-12 20:09
> @bryantbiggs is there a way to check terraform version in the code and modify the ignore_changes this only if version >=1.2 or is that too dirty? this can be done temporarily i guess, until eventually everyone upgrades to 1.3 and we can apply a permanent "fix" in future releases of the module.

Unfortunately, no. There isn't any dynamic routes that I know of that would support this

**Comment by bryantbiggs** [comment] 2022-06-18 22:18
After thinking about this a bit more, I think we can accommodate a change for this. PR is coming

**Comment by antonbabenko** [comment] 2022-06-19 12:02
This issue has been resolved in version 18.24.1 :tada:

**Closed** 2022-06-19 12:02 UTC
