### ISSUE TITLE
Warning using AWS EKS module

### ISSUE THREAD

**Issue by jordanandres1** [terraform-aws-modules/terraform-aws-eks#2088] opened 2022-05-25 23:41 UTC
## Description

Warning using aws eks module

## Versions

- Module version: 18.21.0

- Terraform version: 1.2.1
- Provider version(s):
    aws = {
      source  = "hashicorp/aws"
      version = "4.15.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.11.0"
    }

## Reproduction Code

Simple use of module in a project

## Expected behavior

No warnings

## Actual behavior

`Warning: Redundant ignore_changes element  on .terraform/modules/eks_cluster/main.tf line 305, in resource "aws_eks_addon" "this": 305: resource "aws_eks_addon" "this" {
Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has been created, retaining the value originally configured. The attribute modified_at is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute in ignore_changes has no effect. Remove the attribute from ignore_changes to quiet this warning.`

**Comment by bryantbiggs** [comment] 2022-05-25 23:57
Duplicate of #2081

**Closed by bryantbiggs** 2022-05-25 23:57 UTC
