### ISSUE TITLE
coredns pods stuck in Pending status. 

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2069] opened 2022-05-11 13:32 UTC
I am trying to create only fargate based cluster and facing issue at coreDNS addon

coreDNS deployment takes a long time (20 min) and fails 1st time..,...however **2nd time terraform apply** works fine.

Error:-
Error: unexpected EKS add-on (eks-test-eu:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE, CREATE_FAILED' (last state: 'CREATING', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration

I have already read : https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

**Comment by bryantbiggs** [comment] 2022-05-11 13:48
Can you share your reproduction code and what steps you have taken to provision?

**Comment by raghavgupta0** [comment] 2022-05-12 05:56
[
[main.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/8675331/main.txt)
](url)

**Comment by raghavgupta0** [comment] 2022-05-16 04:46
Hi All,

can anyone help!!!!!

**Comment by clbx** [comment] 2022-05-16 19:53
I have a similar issue. On first apply, core-dns times out for 20 minutes and is shown in a degraded state in the EKS Web UI. 

On second apply, Core DNS changes to an active state, and the terraform apply finishes. 


Relevant parts of my eks terraform module:

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = "eks-cluster"
  cluster_version = "1.22"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access = true

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  # Self managed node groups will not automatically create the aws-auth configmap so we need to
  create_aws_auth_configmap = true
  manage_aws_auth_configmap = true

  # Extend cluster security group rules
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }

  # Extend node-to-node security group rules
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }

  self_managed_node_groups = {

    #This is 1 m5.xlarge node. May want to expand in the future.
    default_node_group = {}
  }

...

resource "aws_eks_addon" "coredns" {
  cluster_name      = module.eks.cluster_id
  addon_name        = "coredns"
  resolve_conflicts = "OVERWRITE"
  depends_on = [
    module.eks
  ]
}
```

**Comment by romich** [comment] 2022-05-16 20:01
+1, also seen this. The reason for degraded state, as reported by `aws eks describe-addon`, is:
```
        "health": {
            "issues": [
                {
                    "code": "InsufficientNumberOfReplicas",
                    "message": "The add-on is unhealthy because it doesn't have the desired number of replicas."
                }
            ]
        }
```
But both replicas are running fine:
```
❯ k -n=kube-system describe deployments.apps coredns
Name:                   coredns
...
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
```
```
❯ k get pods -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   aws-node-qjttf             1/1     Running   0          2m37s
kube-system   coredns-7cc879f8db-6gxg4   1/1     Running   0          9m54s
kube-system   coredns-7cc879f8db-zrt7n   1/1     Running   0          9m54s
kube-system   kube-proxy-2cdv7           1/1     Running   0          2m37s
```
Not sure if it's modules's fault though.

**Comment by raghavgupta0** [comment] 2022-05-17 06:29
In my case, I want to create a cluster with Fargate profile only and get an issue with coreDNS deployment.

**Comment by raghavgupta0** [comment] 2022-05-17 11:47
yes... I have used this patch under null resource but we don't want to use null_resource.
so is there any solution within module/resource,

**Comment by bryantbiggs** [comment] 2022-05-17 11:49
> yes... I have used this patch under null resource but we don't want to use null_resource. so is there any solution within module/resource,

No - https://github.com/hashicorp/terraform-provider-kubernetes/issues/723

**Comment by cmanfre4** [comment] 2022-05-19 17:40
> yes... I have used this patch under null resource but we don't want to use null_resource. so is there any solution within module/resource,

Sort of:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/723#issuecomment-1130887972

**Comment by bryantbiggs** [comment] 2022-06-02 13:40
Closing this out for now unless there is any new information to add. For running CoreDNS on fargate only clusters please see https://github.com/clowdhaus/eks-reference-architecture/tree/main/serverless

**Closed by bryantbiggs** 2022-06-02 13:40 UTC
Labels: question
