### ISSUE TITLE
map_users has been removed from v18

### ISSUE THREAD

**Issue by hasinireddy24** [terraform-aws-modules/terraform-aws-eks#1955] opened 2022-03-23 09:50 UTC
Hi, 

I wanted to add the map_users varaible in the eks module. I see that map_users has been removed from v18, instead of using map_users what is the replacement for that to use in module eks. 

Please let me help me with the replacement variable for map_users.

Thanks in advance!

**Comment by bryantbiggs** [comment] 2022-03-23 11:02
duplicate of #1901

**Closed by bryantbiggs** 2022-03-23 11:02 UTC
