### ISSUE TITLE
Updates needed for Terraform 0.15

### ISSUE THREAD

**Issue by dak1n1** [terraform-aws-modules/terraform-aws-eks#1240] opened 2021-02-12 21:59 UTC
# I have issues

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The EKS module works great for Terraform 0.14, but there are some upcoming changing in 0.15 that I wanted to bring to your attention since I ran into issues when testing it yesterday.

The module uses a function called `list()` in several places. This function is deprecated in Terraform 0.12 and has been removed in Terraform 0.15, and replaced with a function called `tolist()`.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Download one of the Terraform 0.15 builds from [here](https://releases.hashicorp.com/terraform/). 

```
$ terraform version
Terraform v0.15.0-alpha20210210
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v9.9.9
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Try to `terraform init` and `terraform plan` with a configuration containing the terraform-aws-eks module. ([Here's my config](https://github.com/hashicorp/terraform-provider-kubernetes/tree/master/_examples/eks), in case you need it). You'll see errors such as this:

```
$ terraform plan
╷
│ Error: Error in function call
│
│   on .terraform/modules/cluster/outputs.tf line 3, in output "cluster_id":
│    3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ])
│ syntax to write a literal list.
╵
```

## What's the expected behavior?

`terraform plan` should succeed and the module should use `tolist()` instead of `list()`.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No, I can't commit to fixing this, but I did give it a try. I can tell you a little about what I did:

First, I opened up my IDE (Goland) and hit ctrl+shift+R, which brought up the find & replace dialog. Since that dialog allows the use of regex with back-referencing, it can replace the `list()` statements accurately and easily across many files.

This is the regex of what is being replaced:

```
element\(concat\((.*)\, list\(\"\"\)\)\, 0\)
```

I replaced it with this:

```
tolist(concat(element($1),0))
```

I tried reordering the `tolist`, `concat`, `element` functions a bit... I did some experimenting with it, but I don't know enough about the data being returned and how it's used. I got stuck here:

```
│ Error: Invalid function argument
│
│   on .terraform/modules/cluster/outputs.tf line 66, in output "cloudwatch_log_group_arn":
│   66:   value       = element(concat(aws_cloudwatch_log_group.this[*].arn, tolist("")), 0)
│
│ Invalid value for "v" parameter: cannot convert string to list of any single type.
```

## Environment details

* Affected module version: v14.0.0
* OS: Fedora 33
* Terraform version: 0.15 alpha

## Any other relevant info

```
$ terraform init
Initializing modules...
Downloading terraform-aws-modules/eks/aws 14.0.0 for cluster...
- cluster in .terraform/modules/cluster
- cluster.fargate in .terraform/modules/cluster/modules/fargate
- cluster.node_groups in .terraform/modules/cluster/modules/node_groups
- kubernetes-config in kubernetes-config
- vpc in vpc
```

**Comment by jochen-st** [comment] 2021-02-20 20:53
I think replacing `list("")` with `[""]` should work. 

To make it work using `tolist()` Terraform seems to need `tolist([""])` which looks redundant.

**Comment by jochen-st** [comment] 2021-02-27 14:59
Duplicate of #1164 , PR in #1165

**Comment by antonbabenko** [comment] 2021-04-16 08:06
Terraform 0.15 is supported in version [v15.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v15.0.0) that has been just released.

For the previous version of Terraform please use this module version `~> 14.0`.

Let us know if there are any issues with this release.

**Closed by antonbabenko** 2021-04-16 08:06 UTC
