### ISSUE TITLE
EBS CSI driver: unauthorized (when deploying in CI/CD)

### ISSUE THREAD

**Issue by mark-ship-it** [terraform-aws-modules/terraform-aws-eks#2721] opened 2023-08-11 17:16 UTC
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 18.26.6 and 19.16.0

- Terraform version:

1.4.5

- Provider version(s):

the relevant subset:
```
│   └── module.eks
│       ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
│       ├── provider[registry.terraform.io/hashicorp/tls] ~> 3.0
│       ├── provider[registry.terraform.io/hashicorp/kubernetes] >= 2.10.0
│       ├── module.self_managed_node_group
│           ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
│           └── module.user_data
│               └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
│       ├── module.eks_managed_node_group
│           ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
│           └── module.user_data
│               └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
│       ├── module.fargate_profile
│           └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
│       └── module.kms
│           └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
```
## Reproduction Code [Required]

creating the EKS cluster
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.16.0"

  cluster_name    = var.eks_cluster_name
  cluster_version = var.eks_cluster_version

  kms_key_administrators = var.kms_key_administrators

  vpc_id     = var.vpc_id
  subnet_ids = local.eks_subnet_ids

  cluster_endpoint_private_access = var.eks_endpoint_private_access
  cluster_endpoint_public_access = var.eks_endpoint_public_access

  # Temp workaround for bug : double owned tag 
  # https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1810
  node_security_group_tags = {
    "kubernetes.io/cluster/${var.eks_cluster_name}" = null
  }

  eks_managed_node_group_defaults = {
    ami_type                              = "AL2_x86_64"
    key_name                        = var.aws_keypair_name
    attach_cluster_primary_security_group = true
    # Disabling and using externally provided security groups
    create_security_group = false
    vpc_security_group_ids = var.eks_vpc_security_groups
    iam_role_name = "${var.eks_cluster_name}_ng"
    block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = var.eks_node_disk_size
            volume_type           = "gp3"
          }
        }
    }
  }

  eks_managed_node_groups = local.node_groups

  tags = merge({
    Name    = var.eks_cluster_name},
    var.tags
  )
}
```
creating the EBS CSI driver
```
resource "aws_iam_role" "ebs_csi_iam_role" {
  name = "dockyard-ebs-csi-iam-role"
  assume_role_policy = jsonencode({
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": module.eks.oidc_provider_arn
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${module.eks.oidc_provider}:aud": "sts.amazonaws.com",
          "${module.eks.oidc_provider}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
        }
      }
    }
  ]
})
}

resource "aws_iam_role_policy_attachment" "ebs_csi_iam_role_policy_attach" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  role       = aws_iam_role.ebs_csi_iam_role.name
  depends_on = [aws_iam_role.ebs_csi_iam_role]
}

resource "aws_eks_addon" "aws-ebs-csi-driver" {
  depends_on = [aws_iam_role.ebs_csi_iam_role]
  cluster_name  = "${var.eks_cluster_name}"
  addon_name    = "aws-ebs-csi-driver"
  addon_version = "v1.17.0-eksbuild.1"
  service_account_role_arn = "${aws_iam_role.ebs_csi_iam_role.arn}"
}

resource "kubernetes_storage_class" "gp3" {
  metadata {
    name = "gp3"
  }
  storage_provisioner = "kubernetes.io/aws-ebs"
  reclaim_policy      = "Delete"
  parameters = {
    type = "gp3"
    fsType = "ext4"
  }
  allow_volume_expansion = true
  volume_binding_mode = "WaitForFirstConsumer"
}
```

no

this is a problem in CI/CD (github actions), so there is no local cache

deployed via laptop (works fine), but when i introduce another principal to deploy it, i run into a problem.  I can reproduce when i assume the CI/CD role and run an apply

## Expected behavior

after the summary of the plan, i expect terraform to return a code of 0 and terminate

## Actual behavior
terraform plan returns an error:

terraform plan
...
all output is as expected
...
Plan: 25 to add, 74 to change, 19 to destroy.
Releasing state lock. This may take a few moments...
Error: Process completed with exit code 1.

Error: Unauthorized

  with module.dockyard.kubernetes_storage_class.gp3,

  on .terraform/modules/dockyard/terraform/[eks-addon.tf](http://eks-addon.tf/) line 37, in resource "kubernetes_storage_class" "gp3":

  37: resource "kubernetes_storage_class" "gp3" {

This seems to be a permissions issue of having multiple principals deploying the EBS CSI driver.  I filed a ticket with Amazon support, and the IAM roles seem to be set up properly.

**Comment by bryantbiggs** [comment] 2023-08-11 17:25
I don't see anything related to EBS is the code supplied - where is the full reproduction

**Comment by mark-ship-it** [comment] 2023-08-11 17:34
@bryantbiggs , sorry for not including the EBS CSI driver code.  I added some additional code for how we instantiate the driver.  Thanks for taking a look, and letting me know what else I can provide.

**Comment by bryantbiggs** [comment] 2023-08-11 17:45
FYI - https://github.com/bryantbiggs/how-to-create-reproduction#why-is-it-proper

**Comment by maxkokocom** [comment] 2023-08-31 21:29
I am not sure do I have the same issue, but could you please provide more explicit examples of how to enable EBS CSI driver? 

I did the following and got unauthorised in my csi pod.

Added module as in the example:
```hcl
module "ebs_csi_irsa_role" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name             = "ebs-csi-${local.cluster_name}"
  attach_ebs_csi_policy = true

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:ebs-csi-controller-sa"]
    }
  }

  tags = local.tags
}
```

Added addon in the addons list:
```hcl
  cluster_addons = {
    coredns    = {}
    kube-proxy = {}
    vpc-cni    = {}
    aws-ebs-csi-driver = {}
  }
```

Role seems to be created, pod seems to be working, but when PVC is beign created I get the following:

```
rpc error: code = Internal desc = Could not create volume "pvc-80170482-10e6-4914-9a1b-8b37052b333a": could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation.
```

I wonder am I doing something wrong or maybe the roles in the module are not correctly assigned?

**Comment by bryantbiggs** [comment] 2023-08-31 21:31
https://github.com/clowdhaus/eks-reference-architecture/blob/main/ephemeral-vol-test/eks.tf

**Comment by bryantbiggs** [comment] 2023-09-21 11:37
please see the referenced examples above - this appears to be an issue with how you have configured IRSA so closing out this issue here

**Closed by bryantbiggs** 2023-09-21 11:37 UTC
Labels: question
