### ISSUE TITLE
Failed to destroy eks1.17 cluster, error message: Error: Your query returned no results. Please change your search criteria and try again.

### ISSUE THREAD

**Issue by alisachen** [terraform-aws-modules/terraform-aws-eks#1884] opened 2022-02-17 07:01 UTC
## Description

I have a eks1.17 cluster, which create by terraform-aws-eks cluster, and i want to destroy it, but failed.

only alert error message as below,
Error: Your query returned no results. Please change your search criteria and try again.

can't fixed.
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: >= 0.12.0

 - Provider(s):  v0.13.1

 - Module: 1.11.3

## Reproduction

terraform destroy

## Expected behavior

destroy the eks1.17 cluster
## Actual behavior

can't destroy it

**Comment by daroga0002** [comment] 2022-02-17 07:56
please provide more logs from terraform execution

**Comment by alisachen** [comment] 2022-02-17 08:15
module.eks.aws_iam_instance_profile.workers_launch_template[6]: Refreshing state... [id=usw2c2-dev-eks202103010813028
module.eks.aws_iam_instance_profile.workers_launch_template[13]: Refreshing state... [id=usw2c2-dev-eks20210906101257
data.aws_eks_cluster_auth.cluster: Refreshing state... [id=2021-11-08 02:33:39.828888755 +0000 UTC]
data.aws_eks_cluster.cluster: Refreshing state... [id=usw2c2-dev-eks]
module.eks.kubernetes_config_map.aws_auth[0]: Refreshing state... [id=kube-system/aws-auth]

Error: Your query returned no results. Please change your search criteria and try again.


Releasing state lock. This may take a few moments...

@daroga0002  no any other logs, except the above info

**Comment by alisachen** [comment] 2022-02-18 12:10
@daroga0002  thanks for your feedback, and i try your solution, but it also can't be destroy by the same error
module.eks.aws_iam_instance_profile.workers_launch_template[3]: Refreshing state... [id=usw2c2-dev-eks20210301081302864300000010]
module.eks.aws_iam_instance_profile.workers_launch_template[12]: Refreshing state... [id=usw2c2-dev-eks20210906101257411400000003]
Error: Your query returned no results. Please change your search criteria and try again.
Releasing state lock. This may take a few moments..._

and i continue to remove the module.eks.aws_iam_instance_profile.workers_launch_template[12] tf.state, then also can't be destroyed with the same error

I still can't find solution.

**Comment by bryantbiggs** [comment] 2022-02-18 13:31
closing due to lack of information/reproduction

**Closed by bryantbiggs** 2022-02-18 13:31 UTC
Labels: question, needs update
