### ISSUE TITLE
Crash when destroying but the VPC doesn't exist

### ISSUE THREAD

**Issue by karolinepauls** [terraform-aws-modules/terraform-aws-eks#449] opened 2019-07-29 15:47 UTC
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy
## What is the current behavior?

Terraform destroy crashes if the VPC doesn't exist any more.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. Create an EKS cluster.
2. Add some state that will fail deleting, e.g. a add a TF-managed hosted zone and insert some records to it manually
3. `terraform destroy`
4. Destroy will successfully delete the cluster and fail to delete the zone.
5. `terraform destroy` again.
6. Destroy will fail with the zone error and:

```
Error: Error in function call

  on .terraform/modules/eks/terraform-aws-modules-terraform-aws-eks-9c3d222/local.tf line 6, in locals:
   6:   cluster_security_group_id = coalesce(
   7:
   8:
   9:
    |----------------
    | aws_security_group.cluster is empty tuple
    | var.cluster_security_group_id is ""

Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

(I think that's the way it should be possible to reproduce it)

## What's the expected behavior?

It would be nice to accept resources not existing when destroying.

## Environment details

* Affected module version: 5.0.0
* OS: Ubuntu 19.04
* Terraform version: `v0.12.5`

**Comment by max-rocket-internet** [comment] 2019-07-30 13:12
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/402

**Closed by max-rocket-internet** 2019-07-30 13:12 UTC
