### ISSUE TITLE
Error: Post "https://xxx/api/v1/namespaces/kube-system/configmaps": dial tcp xxx:443: i/o timeout

### ISSUE THREAD

**Issue by cpini** [terraform-aws-modules/terraform-aws-eks#941] opened 2020-07-04 15:27 UTC
Hi,

I'm trying to setup a k8s cluster via learn-terraform-provision-eks-cluster which uses this module to build the cluster out and it's consistently failing here:-
```
Error: Post "https://xxxx/api/v1/namespaces/kube-system/configmaps": dial tcp xxxx:443: i/o timeout

  on .terraform/modules/eks/aws_auth.tf line 62, in resource "kubernetes_config_map" "aws_auth":
  62: resource "kubernetes_config_map" "aws_auth" {
```
Any help greatly appreciated - thanks.

Output of `terraform version` below and I'm using awscli 2.0.28

Thanks

Terraform v0.12.24
+ provider.aws v2.69.0
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

**Comment by dpiddockcmp** [comment] 2020-07-06 15:36
Hi. You need to configure the kubernetes provider in order for the module to communicate with the new cluster. The [learn-terraform-provision-eks-cluster](https://github.com/hashicorp/learn-terraform-provision-eks-cluster) example is incomplete and appears to be abandoned. 

Your issue has already been raised on that repo https://github.com/hashicorp/learn-terraform-provision-eks-cluster/issues/12
And a PR with a fix submitted https://github.com/hashicorp/learn-terraform-provision-eks-cluster/pull/4

Alternatively, refer to this module's Usage example in the README:
```hcl
data "aws_eks_cluster" "cluster" {
  name = module.my-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.my-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.16"
  subnets         = ["subnet-abcde012", "subnet-bcde012a", "subnet-fghi345a"]
  vpc_id          = "vpc-1234556abcdef"

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]
}
```

Closing this as it's a duplicate of #853

**Closed by dpiddockcmp** 2020-07-06 15:36 UTC
