### ISSUE TITLE
cannot use GP3 root volumes 

### ISSUE THREAD

**Issue by exavier-slf** [terraform-aws-modules/terraform-aws-eks#1244] opened 2021-02-16 16:32 UTC
# I have issues

## I'm submitting a...

* [ ] bug report

## What is the current behavior?

Launch configuration  creates gp3 based volumes by default , cannot change volume type

## If this is a bug, how to reproduce? Please include a code sample if relevant.

terraform apply errors out and says gp3 not a valid volume type and we cannot change the volume type from  variables

Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
        status code: 400, request id: 53374bce-054f-4b8a-87be-e0f85ddbe98f

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by calvinbui** [comment] 2021-02-17 04:38
the default aws-ebs storage class doesn't support gp3

you have to use the new ebs csi: https://github.com/kubernetes-sigs/aws-ebs-csi-driver 

related: https://github.com/aws/containers-roadmap/issues/1187

**Comment by Justin-DynamicD** [comment] 2021-02-22 19:30
Adding my voice to this as this is odd news to me.

I currently have 4 eks cluster deployed the same way with gp3 root volumes in one account.

Went to spin up a new eks cluster in a new account today (same region) and was greeted wit the same error message about gp3 not being supported.  I'm doing some digging on what's going on ... but this feels new? when did this change happen?

the module itself defaults to GP3 which implies it used to work this way.

**Comment by Justin-DynamicD** [comment] 2021-02-22 20:45
Here is the change made 25 days ago:
https://github.com/terraform-aws-modules/terraform-aws-eks/commit/76537d1b8d89dbe104ec32fb6ddd2d7c084b5e28

Again, I think putting a constraint on the variable to allow gp3 is likely fine, but as-is this change breaks all example configs in this repo aand most deployments as terraform, by nature, is a deploy from scratch tool.

**Comment by rchenzheng** [comment] 2021-02-26 22:28
I am also having the same issues, where does one go about fetching the new CSI? Is it on the newer versions of EKS?

**Comment by rchenzheng** [comment] 2021-02-26 22:31
> Here is the change made 25 days ago:
> [76537d1](https://github.com/terraform-aws-modules/terraform-aws-eks/commit/76537d1b8d89dbe104ec32fb6ddd2d7c084b5e28)
> 
> Again, I think putting a constraint on the variable to allow gp3 is likely fine, but as-is this change breaks all example configs in this repo aand most deployments as terraform, by nature, is a deploy from scratch tool.

@Justin-DynamicD You can work around this by defining the `root_volume_type` in the worker_groups

Example:

```
  worker_groups = [
    {
      ...
      root_volume_type = "gp2"
    }
```

**Comment by Justin-DynamicD** [comment] 2021-03-01 17:33
@rchenzheng you are of course correct: I can change the default to gp2 and things work.  I guess my complaint/concern is right now I feel the module no longer has sane defaults, as the default values don't allow you to actually launch the workers.  Someone running the basic example (without adding root_volume_type and runnign as-is) would have to

1. terraform apply (fails to launch workers)
2. use kubectl/helm to deploy latest ebs-csi driver
3. rerun terraform apply (works)

That's just messy.  I would propose that until gp3 support is included in the controller by default that the template should _default_ to gp2 as well.  At the end of the day, maybe this is just a nitpick, but to me a module should only require as few params as possible.

**Comment by rchenzheng** [comment] 2021-03-01 18:00
> @rchenzheng you are of course correct: I can change the default to gp2 and things work. I guess my complaint/concern is right now I feel the module no longer has sane defaults, as the default values don't allow you to actually launch the workers. Someone running the basic example (without adding root_volume_type and runnign as-is) would have to
> 
> 1. terraform apply (fails to launch workers)
> 2. use kubectl/helm to deploy latest ebs-csi driver
> 3. rerun terraform apply (works)
> 
> That's just messy. I would propose that until gp3 support is included in the controller by default that the template should _default_ to gp2 as well. At the end of the day, maybe this is just a nitpick, but to me a module should only require as few params as possible.

I agree, the defaults break all current examples since the provider doesn't support gp3.

**Comment by james-callahan** [comment] 2021-03-23 02:27
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1205

**Closed** 2021-05-28 10:40 UTC
