### ISSUE TITLE
Upgrade to v18.0 triggers the destruction of the entire EKS cluster

### ISSUE THREAD

**Issue by albgus** [terraform-aws-modules/terraform-aws-eks#1784] opened 2022-01-17 10:59 UTC
## Description

I am attempting an upgrade of this module to v18, and after faffing a bit with the parameters to get the plan to work I discovered that it attempts to change the `role_arn` and `vpc_config.security_groups` parameters of the EKS cluster itself, which triggers a re-creation of the entire cluster. This seems like a really major problem as it would destroy all deployments in Kubernetes.

I'm not sure if I'm missing something here, the upgrade guide states that resources _may_ need to be recreated and that these resources _may_ also trigger the re-creation of the cluster. Apart from setting prefix_separator to "" (which doesn't work) it doesn't mention anything about solving this issue.

## Versions
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
 - Module: 18.2.0

## Reproduction
Steps to reproduce the behavior: Upgrade from v17.24.0 -> v18.2.0

## Code snippet to reprocude
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.2.0"

  cluster_name              = var.name
  cluster_version           = var.cluster_version
  subnet_ids                = length(var.control_plane_subnets) > 0 ? var.control_plane_subnets : var.subnets
  vpc_id                    = var.vpc_id
  cluster_service_ipv4_cidr = var.cluster_service_ipv4_cidr

  prefix_separator = ""

  cluster_endpoint_private_access                = true
  cluster_endpoint_public_access                 = false
  cluster_security_group_additional_rules        = merge(
    var.cluster_endpoint_security_group_rules,
    local.cluster_sg_sg_rules,
    local.cluster_sg_cidr_rules
  )
  enable_irsa = true

  cluster_encryption_config = var.encrypted_secrets ? [
    {
      provider_key_arn = aws_kms_key.eks[0].arn
      resources        = ["secrets"]
    }
  ] : null

  cluster_enabled_log_types = var.cluster_logs ? ["api", "audit", "authenticator", "controllerManager", "scheduler"] : null

  self_managed_node_groups        = var.self_managed_node_groups

  self_managed_node_group_defaults = {
    subnets          = length(var.worker_subnets) > 0 ? var.worker_subnets : var.subnets
    root_volume_type = "gp3"
    root_volume_size = "100"
    root_encrypted   = true
  }
}

```

### Terminal Output Screenshot(s)
(Truncated, because there's a LOT of output)

```
  # module.k8s.module.eks.aws_iam_role.cluster[0] will be destroyed
  - resource "aws_iam_role" "cluster" {
      - arn                   = "arn:aws:iam::XXX:role/dev20211202123117646800000004" -> null
[...]
    }

  # module.k8s.module.eks.aws_eks_cluster.this[0] must be replaced
+/- resource "aws_eks_cluster" "this" {
      ~ arn                       = "arn:aws:eks:eu-west-1:XXX:cluster/dev" -> (known after apply)

        ] -> (known after apply)
[...]
      ~ role_arn                  = "arn:aws:iam::XXX:role/dev20211202123117646800000004" -> (known after apply) # forces replacement
      ~ status                    = "ACTIVE" -> (known after apply)
[...]
      ~ vpc_config {
          ~ cluster_security_group_id = "sg-xxx" -> (known after apply)
          ~ security_group_ids        = [
              - "sg-xxx",
            ] -> (known after apply) # forces replacement
          ~ vpc_id                    = "vpc-xxx" -> (known after apply)
            # (4 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }


```

**Comment by daroga0002** [comment] 2022-01-17 11:13
v18 version of module is breaking change, please refer to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md what resources are moved/renamed/removed and you will need to adjust your terraform state as part of upgrade task.

**Comment by albgus** [comment] 2022-01-17 11:46
This is what the upgrade guide says about it:
```
Resource name changes may cause issues with existing resources. For example, security groups and IAM roles cannot be renamed, they must be recreated. Recreation of these resources may also trigger a recreation of the cluster. To use the legacy (< 18.x) resource naming convention, set prefix_separator to "".
```

I've figured out that this is far from complete, and at least the following prevents the security group from being re-created:
```
  iam_role_name                          = var.name
  cluster_security_group_name            = var.name
  cluster_security_group_use_name_prefix = true
  prefix_separator                       = ""
  cluster_security_group_description     = "EKS cluster security group."

```

Now it's just the IAM role left deal with...

I feel that this may be the most important part of the Upgrade documentation, and it's completely missing.

**Comment by bryantbiggs** [comment] 2022-01-17 12:18
duplicate of #1744 - as @daroga0002 stated, this was a breaking change and there are no guarantees of resources not being re-created/modified if users elect to upgrade from v17.x t o v18.x - thats what a breaking change is

**Closed by bryantbiggs** 2022-01-17 12:18 UTC

**Comment by joaosa** [comment] 2022-04-11 18:25
> This is what the upgrade guide says about it:
> 
> ```
> Resource name changes may cause issues with existing resources. For example, security groups and IAM roles cannot be renamed, they must be recreated. Recreation of these resources may also trigger a recreation of the cluster. To use the legacy (< 18.x) resource naming convention, set prefix_separator to "".
> ```
> 
> I've figured out that this is far from complete, and at least the following prevents the security group from being re-created:
> 
> ```
>   iam_role_name                          = var.name
>   cluster_security_group_name            = var.name
>   cluster_security_group_use_name_prefix = true
>   prefix_separator                       = ""
>   cluster_security_group_description     = "EKS cluster security group."
> ```
> 
> Now it's just the IAM role left deal with...
> 
> I feel that this may be the most important part of the Upgrade documentation, and it's completely missing.

`iam_role_arn` instead of `iam_role_name` should do it 👍

**Comment by dbirks** [comment] 2022-04-26 03:39
For future travelers, I found I had to set `create_iam_role = false` as well. End result is something like:

```
  create_iam_role                    = false
  iam_role_arn                       = "arn:aws:iam::000000000000:role/dev00000000000000000000000000"
  prefix_separator                   = ""
  cluster_security_group_name        = var.name
  cluster_security_group_description = "EKS cluster security group."
```
