### ISSUE TITLE
Sometimes using the Karpenter module errors with `Invalid for_each argument`

### ISSUE THREAD

**Issue by sapslaj** [terraform-aws-modules/terraform-aws-eks#2579] opened 2023-04-18 15:56 UTC
## Is your request related to a problem? Please describe.

Under certain cases Terraform thinks that the `for_each` used for `aws_iam_role_policy_attachment.this` in the [karpenter](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/karpenter) submodule cannot determine the keys until after apply.

```
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/karpenter.karpenter/modules/karpenter/main.tf line 340, in resource "aws_iam_role_policy_attachment" "this":
│  340:   for_each = { for k, v in toset(compact([
│  341:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  342:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  343:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  344:   ])) : k => v if local.create_iam_role }
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.create_iam_role is true
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.iam_role_attach_cni_policy is true
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so
│ Terraform cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and
│ place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value
│ depends on, and then apply a second time to fully converge.
```

This means one has to `-target` apply things until it is happy but this is very messy in a CI workflow.

## Describe the solution you'd like.

Ideally, instead of using a `list(string)` and passing that through `toset()` we could use a `map(string)` like how `aws_iam_role_policy_attachment.irsa_additional` is built. Maybe like...

```terraform
  for_each = local.create_iam_role ? merge(
    {
      AmazonEKSWorkerNodePolicy          = "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy"
      AmazonEC2ContainerRegistryReadOnly = "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly"
    },
    var.iam_role_attach_cni_policy ? { CNIPolicy = local.cni_policy } : {},
  ) : {}
```

In theory this wouldn't be a breaking change for _new_ infra but it would cause a bit of churn with existing infra since it would have to delete and recreate those policy attachments without some `moved` blocks.

## Additional context

I haven't been able to pinpoint exactly where and why this happens yet. Target applying the `eks` module (instantiation of the top level `terraform-aws-eks` module) seems to help usually. It might be because we have to have a few explicit `depends_on`s so that CRDs are applied to the cluster before resources that use those CRDs.

**Comment by bryantbiggs** [comment] 2023-04-18 16:41
please provide reproduction code - also, ensure you are not using `depends_on` in the module definition which causes this issue

**Comment by sapslaj** [comment] 2023-04-18 19:17
> please provide reproduction code 

I was working on it yesterday but couldn't get it to reliably happen outside of my company's config, hence the lack of reproduction code. I figured since the error was relatively obvious I could inquire about it. I can work on trying to a reliable reproduction example.

> also, ensure you are not using `depends_on` in the module definition which causes this issue

If `depends_on` is the culprit then that's probably the issue. Like I mentioned we have to do that in our config to make sure things are applied in the correct order (especially CRDs). That said we have a module that contains both the karpenter module here, the `helm_release` resource, and some other stuff that then gets added to the root module for our cluster configurations and _that_ module has a `depends_on` in the module definition.

Would it be useful to consider this a feature request to support `depends_on` then?

**Comment by bryantbiggs** [comment] 2023-04-18 20:36
if you would like to work on contributing to Terraform core, please feel free ! https://github.com/hashicorp/terraform/issues/26383#issuecomment-699149145

It is very rare where `depends_on` needs to rely on a module today if the flow of outputs are correctly mapped to downstream attributes. closing this for now though since its not a module issue

**Closed by bryantbiggs** 2023-04-18 20:36 UTC
Labels: question
