### ISSUE TITLE
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable #2

### ISSUE THREAD

**Issue by agelosnm** [terraform-aws-modules/terraform-aws-eks#2618] opened 2023-05-16 15:04 UTC
I'm opening this issue as the previous one https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1234 has been closed with no any proper answer given.

I have an EKS project that was working fine before 2 months. Now, when I try to apply same now I get this issue...

    terraform {
    
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "4.67.0"
        }
    
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "2.20.0"
        }
    
        helm = {
          version = "2.9.0"
        }
      }
    }
    
    provider "kubernetes" {
      host                   = module.eks.cluster_endpoint
      cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
      token                  = module.eks.cluster_token
    }
    
    provider "helm" {
      kubernetes {
        host                   = module.eks.cluster_endpoint
        cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    
        exec {
          api_version = "client.authentication.k8s.io/v1beta1"
          args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
          command     = "aws"
        }
      }
    }

I also tried token authentication.

**Comment by bryantbiggs** [comment] 2023-05-16 15:21
Please provide a full reproduction

**Comment by agelosnm** [comment] 2023-05-17 07:24
> Please provide a full reproduction

I'm running this on Terraform Cloud with version 1.4.6 (older versions giving the issue too). Also tried other versions of the providers.

**Comment by agelosnm** [comment] 2023-05-17 07:26
> > Please provide a full reproduction
> 
> I'm running this on Terraform Cloud with version 1.4.6 (older versions giving the issue too). Also tried other versions of the providers.

the AWS keys I use are having full access to everything in AWS

**Comment by bryantbiggs** [comment] 2023-05-17 13:04
I don't need access keys or access to your environment (nor should you share that with external parties!) - I just need the configuration you are using

**Comment by bryantbiggs** [comment] 2023-06-07 00:26
closing this issue for now since I am unable to help triage or troubleshoot without a reproduction

**Closed by bryantbiggs** 2023-06-07 00:26 UTC
Labels: question
