### ISSUE TITLE
`resolve_conflicts` is deprecated in v5+ of the aws provider; usage in eks module leads to error when adding addons

### ISSUE THREAD

**Issue by life5ign** [terraform-aws-modules/terraform-aws-eks#2825] opened 2023-11-21 01:53 UTC
This line:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ec454c51cb0026254b68cafe7aa9d05f873af990/main.tf#L399C1-L400C1

Leads to the error
```
│ Warning: Argument is deprecated
│ 
│   with module.eks.aws_eks_addon.this["kube-proxy"],
│   on .terraform/modules/eks/main.tf line 399, in resource "aws_eks_addon" "this":
│  399:   resolve_conflicts        = try(each.value.resolve_conflicts, "OVERWRITE")
│ 
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or
│ "resolve_conflicts_on_update" instead
│ 
│ (and one more similar warning elsewhere)
```

When creating or adding these addons to a cluster that doesn't have them (it only has the self managed, K8s versions of them)

```hcl
module "eks" {
  # .......

  cluster_addons = {
      coredns = {
        most_recent = true
        resolve_conflicts = 
      }
      kube-proxy = {
        most_recent = true
      }
  }
}
```

**Comment by bryantbiggs** [comment] 2023-11-21 02:04
its a warning, not an error - closing as a duplicate of #2635

**Closed by bryantbiggs** 2023-11-21 02:04 UTC

**Comment by life5ign** [comment] 2023-11-21 02:35
just saw that, thanks for looking into it
