### ISSUE TITLE
Add support for "preserve" argument for addons

### ISSUE THREAD

**Issue by romich** [terraform-aws-modules/terraform-aws-eks#2054] opened 2022-05-03 09:50 UTC
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: 4.10.0

## Describe the solution you'd like.
Add support for `preserve` argument in `resource "aws_eks_addon"`, similar to other arguments.

## Describe alternatives you've considered.
Managing addons out of the module.

## Additional context
I understand that AWS v4 has significant breaking changes and not all people can or want to upgrade (though v4.9.0 has improvements in this regard), so for now just probing whether setting min version of aws provider to 4.10.0 in this module is something that would be considered.

**Comment by bryantbiggs** [comment] 2022-05-03 11:47
marking as duplicate of #1908 - when that is added this functionality will be supported as well

**Comment by bryantbiggs** [comment] 2022-05-03 11:48
actually keeping it open since its not same source 😅

**Closed** 2022-12-05 21:26 UTC
Labels: on hold, breaking change
