### ISSUE TITLE
Cannot add RBAC for "system:masters" with new access_entries configuration

### ISSUE THREAD

**Issue by jordan-fabric** [terraform-aws-modules/terraform-aws-eks#2915] opened 2024-02-07 20:41 UTC
## Description

I've just updated my Terraform to use the `20.2.0` version of this module. I am building a net new cluster, so not upgrading from the `19.x` release.

When trying to add SSO roles to the `system:masters` group I get this:
```
│ Error: creating EKS Access Entry (<ROLE_ARN>): operation error EKS: CreateAccessEntry, https response error StatusCode: 400, RequestID: <REQUEST_ID>, InvalidParameterException: The kubernetes group name system:masters is invalid, it cannot start with system:
```

For <ROLE_ARN> I have tried with the prefix removed for `/aws-reserved/sso.amazonaws.com` as this was needed for the `configmap/aws-auth` to work, as well as the full ARN leaving that intact. Neither works but I had tried to ensure I had 100% parity with the config I had before.

This is the same behavior even through the UI, for either `system:masters` or even trying to mimic the automatically created `system:nodes` that got provisioned, says `system` cannot be used.

I have also tried to see if it is a misnomer and used the [ClusterRole named cluster-admin](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) which the binding should be associated with, but it appears to be invalid for this resource (which makes sense, was just a shot in the dark).

If your request is for a new feature, please use the `Feature request` template.

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

Done all of the following steps already.

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.2.0

- Terraform version: 1.7.2 (also tried using 1.6.6 before upgrading)
- Provider version(s):
  - provider registry.terraform.io/hashicorp/aws v5.35.0
  - provider registry.terraform.io/hashicorp/cloudinit v2.3.3
  - provider registry.terraform.io/hashicorp/helm v2.12.1
  - provider registry.terraform.io/hashicorp/kubernetes v2.25.2
  - provider registry.terraform.io/hashicorp/time v0.10.0
  - provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]
Old Code:
```
  manage_aws_auth_configmap = true
  aws_auth_roles = concat(
    [{
      groups = [
        "system:bootstrappers",
        "system:nodes",
      ]
      rolearn  = module.eks_blueprints_addons.karpenter.node_iam_role_arn
      username = "system:node:{{EC2PrivateDNSName}}"
    }],
  local.aws_auth_roles)


locals {
  # extrapolates the ARNs; this is based on the terraform examples on their site for the data source of iam_roles
  devops_admin_role_arns = [
    for parts in [for arn in data.aws_iam_roles.devops_admin_roles.arns : split("/", arn)] :
    format("%s/%s", parts[0], element(parts, length(parts) - 1))
  ]

  # set the configmap/aws-auth syntax mapping of the DevOps users to K8s "masters" (or admins)
  aws_auth_roles = [
    {
      rolearn  = replace(local.devops_admin_role_arns[0], "/aws-reserved/sso.amazonaws.com", "")
      username = "devopsadmin"
      groups   = ["system:masters"]
    }
  ]

}
```
New code:
```
  access_entries = {
    devops = {
      principal_arn     = "arn:aws:iam::<ACCOUNT_ID>:role/AWSReservedSSO_RoleName_SomeLongArseUID"
      kubernetes_groups = ["system:masters"]
    }
  }
```

I hard-coded it just to make sure that I am not falling victim to data transform issues in my `locals.tf` but the issue is not the ARN so much as the actual `kubenernetes_groups` definition.

 
Yes. `terraform workspace -select-or-create <CLUSTER_NAME>` where the `workspace_key_prefix=workspaces/eks/$TF_VAR_account_id` for a `S3` remote backend.
 
Yes, several times. Local creds, all the things that I know of that ineract with Terraform.
 
1. Update the code block in `main.tf` to use the `access_entries` block provided in my [Reproduction Code](#reproduction-code)
2. Clear local files: `for item in .vscode* .terraform* terraform* *tfplan* *errored*; do rm -rf "$item";  done`
3. `terraform init -reconfigure -backend-config "workspace_key_prefix=workspaces/eks/$TF_VAR_account_id"`
4. `terraform workspace -select-or-create $TF_VAR_name`
5. `terraform plan -out tfplan` -> successful
6. `terraform apply`
7. Sweet sweet error life

## Expected behavior

Have a viable replacement for the soon-to-be-deprecated `manage_aws_auth_configmap` where entries are translatable. 

## Actual behavior

InvalidParameterException: The kubernetes group name system:masters is invalid, it cannot start with system:

### Terminal Output Screenshot(s)
<img width="1247" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/149408992/198b9476-fb5f-4749-8f66-a8a36a9f3d4d">

## Additional context

Seems like there are relatively few examples, and even then they require the `policy_arn` and attachments; if there is an equivalent using that it would be great to see it. However, it seems a bit counterintuitive, and thus far even attaching the `EKSAdminPolicy` as an option does not give my SSO role API access to the cluster.

**Comment by jordan-fabric** [comment] 2024-02-07 21:49
So I am not sure if it is a UI bug or something (screenshot at the bottom)? I have the following code snippet now:
```
  access_entries = {
    devops = {
      type          = "STANDARD"
      user_name     = "devopsadmin"
      cluster_name  = module.eks.cluster_name
      principal_arn = "arn:aws:iam::<ACCOUNT_ID>:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_RoleName_SomeLongArseUID"
      policy_arn    = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
    }
  }
```

Now I no longer get credential/access issue with something like `kubectl get nodes`:
```
k get node
NAME                         STATUS   ROLES    AGE   VERSION
ip-10-9-3-175.ec2.internal   Ready    <none>   3h    v1.29.0-eks-a5ec690
```
<img width="2888" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/149408992/ab20011f-cd64-4ae5-98d1-3e6b0cdc4999">


The Terraform applies, and I seem to have access, but nothing noting what policies are attached either way. I had the same experience if I commented that out of the Terraform code and did this in the UI.

**Comment by bryantbiggs** [comment] 2024-02-08 00:06
I would suggest reading up on cluster access entries - this blog covers a lot of the necessary details https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/

closing this for now since its not a module issue and the module is working as intended

**Closed by bryantbiggs** 2024-02-08 00:06 UTC
Labels: question
