### ISSUE TITLE
Invalid dynamic for_each value

### ISSUE THREAD

**Issue by ThatDeveloper** [terraform-aws-modules/terraform-aws-eks#1833] opened 2022-02-02 20:57 UTC
## Description

When following 1:1 your instructions I receive the following error:

```
  cluster_encryption_config         = [{
      provider_key_arn  = var.aws.kms_key_arn
      resources         = ["secrets"]
  }]
```
results to
```
│ Error: Invalid dynamic for_each value
│ 
│   on .terraform/modules/eks/main.tf line 29, in resource "aws_eks_cluster" "this":
│   29:     for_each = toset(var.cluster_encryption_config)
│     ├────────────────
│     │ var.cluster_encryption_config is list of object with 1 element
│ 
│ Cannot use a set of object value in for_each. An iterable collection is
│ required.
```

## Versions

 - Terraform: 1.1.4
 - Provider(s):
Installed hashicorp/tls v3.1.0 (signed by HashiCorp)
Installed hashicorp/cloudinit v2.2.0 (signed by HashiCorp)
Installed hashicorp/aws v3.74.0 (signed by HashiCorp)
Installed hashicorp/null v3.1.0 (signed by HashiCorp)
Installed hashicorp/kubernetes v2.7.1 (signed by HashiCorp)
- Module: 18.2.7

## Reproduction

Just followed the information here: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

**Comment by ThatDeveloper** [comment] 2022-02-02 21:35
Okay, well this is kinda strange. Could it be, that this has something to do with a variable that is marked as `sensitive: true`?
I removed it and now it seems to run through.

**Comment by bryantbiggs** [comment] 2022-02-07 20:49
closing for now since its not reproducible - I've run the examples we provided several times over the past few days (testing PRs/changes) without issue https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6c6841cdb8fdd03feb09ca9e73217ed01a0df4f2/examples/eks_managed_node_group/main.tf#L45

**Closed by bryantbiggs** 2022-02-07 20:49 UTC
Labels: question
