### ISSUE TITLE
Document Mixed Windows/Linux Worker Node Cluster

### ISSUE THREAD

**Issue by Jitsusama** [terraform-aws-modules/terraform-aws-eks#2435] opened 2023-01-31 13:00 UTC
## Is your request related to a new offering from AWS?

No.

## Is your request related to a problem? Please describe.

No. Though I first stumbled into this due to being confused as to how to accomplish this task, but I since figured out how to get it to work by myself.

## Describe the solution you'd like.

I already have an example project using the terraform-aws-eks and terraform-aws-vpc modules up at https://github.com/Jitsusama/example-terraform-eks-mixed-os-cluster. It works and has enabled me to get a mixed Windows/Linux worker node cluster working and I was assuming that including some version of it in this repository would be useful for others.

## Describe alternatives you've considered.

Doing nothing, but that doesn't seem very useful for others who might experience the same hardship I did in getting this to work.

## Additional context

The documentation in AWS for setting this up with their solutions is oblique at best, and doesn't map well to existing examples in this repository. I was thinking that adding this to this repository would be useful for your users.

**Comment by Jitsusama** [comment] 2023-01-31 13:00
FYI; if there is interest, and the repository I linked looks suitable, I don't mind cutting a PR to bring that example into this repository.

**Comment by bryantbiggs** [comment] 2023-01-31 13:50
Duplicate of #2350

**Closed by bryantbiggs** 2023-01-31 13:50 UTC

**Comment by Jitsusama** [comment] 2023-02-03 10:41
> Duplicate of #2350 

I'm confused about how this is a duplicate. I'm offering my services to supply a working solution to help other developers and was wanting to discuss it here before submitting a PR. It is obviously related, but not a duplicate. Would you like for me to restate this information on #2350?

**Comment by bryantbiggs** [comment] 2023-02-03 15:34
there is quite a bit more than just simply adding a linux and windows node group plus the configmap. 
1. Your setup will fail if you add any changes to the `aws-auth` configmap, the module currently does not ensure Windows managed nodegroups are always maintained in the configmap
2. This module defaults to using a custom launch template for managed nodegroups, this support has not been updated for Windows based nodegroups
3. Your example shows self-managed node groups which is not what we are trying to demonstrate here - we are trying to demonstrated Windows based managed nodegroups
4. There is a bit of work that will be involved to ensure the user data functionality now aligns with that of Linux and Bottlerocket variants

**Comment by Jitsusama** [comment] 2023-02-04 14:40
> there is quite a bit more than just simply adding a linux and windows node group plus the configmap. 

There definitely can be. This us not my project, so I don't pretend to be able to dictate what can and should be included. Indeed that's why I started with an issue so it could be discussed before submitting a PR. I have something that worked for me that was not easy to get working and I was hoping to add something to this project to help protect others from going down the same path of pain I went down. I was also thinking that having something was preferable to having nothing. 

> 1. Your setup will fail if you add any changes to the `aws-auth` configmap, the module currently does not ensure Windows managed nodegroups are always maintained in the configmap.

That is something we could document if there is not a workaround. 

> 2. This module defaults to using a custom launch template for managed nodegroups, this support has not been updated for Windows based nodegroups

Which is not a problem when you consider Amazon does not support managed Windows node groups. 

> 3. Your example shows self-managed node groups which is not what we are trying to demonstrate here - we are trying to demonstrated Windows based managed nodegroups

Amazon documentation states that they do not support managed node groups for Windows nodes. Thus it would probably be unwise to sink time into configuring an impossibility. 

> 4. There is a bit of work that will be involved to ensure the user data functionality now aligns with that of Linux and Bottlerocket variants 

Does that stop us from documenting something that works to help out users?

**Comment by bryantbiggs** [comment] 2023-02-04 14:50
- https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/

Again, this will be handled correctly in #2350

**Comment by Jitsusama** [comment] 2023-02-04 17:52
> - https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/

That's wonderful!

**Comment by Jitsusama** [comment] 2023-02-04 17:55
> - https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/
> 
> 
> 
> Again, this will be handled correctly in #2350 

I must say this is my worst experience trying to help out with an open source project to date. Sorry for annoying you and wasting your time.

**Comment by bryantbiggs** [comment] 2023-02-04 18:22
What should I have done differently? The issue I linked and stated that this is a duplicate of clearly states that Windows support was added to EKS managed node groups, it states what the outcome should be:
```
Ability to create EKS managed node groups with Windows based nodes
```

And it adds additional context of what else should go into addressing that issue:

```
Tangentially to this change, we should evaluate if we can better accommodate cloud-config in 
user-data since we will be making changes to support Windows based instances now
```

All of the information was there, you just did not bother reading any of it. Its so easy for folks to open an issue/PR and not do an ounce of legwork or investigation and then get all upset when they didn't get there way

**Comment by bryantbiggs** [comment] 2023-02-07 14:13
@Jitsusama - please see above; any feedback?
