### ISSUE TITLE
data aws_ami "eks_worker" is failing in ap-east-1

### ISSUE THREAD

**Issue by vranystepan** [terraform-aws-modules/terraform-aws-eks#480] opened 2019-08-25 12:29 UTC
# I have issues
We are not able to create EKS cluster in `ap-east-1` due to issues with AMI names.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

With any ami we are getting

```
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/<redacted>/terraform-aws-modules-terraform-aws-eks-6ea3582/data.tf line 19, in data "aws_ami" "eks_worker":
  19: data "aws_ami" "eks_worker" {
```

We suppose that EKS module is [always](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L19) trying to find images (before `workers_group_defaults_defaults` is being merged with `var.workers_group_defaults`) with following [pattern](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L22) but apparently there are no such images in the HK region. 

```
amazon-eks-node-${var.cluster_version}-${var.worker_ami_name_filter}
```

I'm not able to receive any results even with CLI:

```
aws ec2 describe-images \                                                                       
    --filters \
        Name=owner-id,Values=602401143452 \
        Name=virtualization-type,Values=hvm \
        Name=root-device-type,Values=ebs \
        Name=is-public,Values=true \
        Name=name,Values=amazon-eks-node-\* \
    --output text \
    --query 'max_by(Images[], &CreationDate).ImageId' \
--profile=<redacted> \
--region=ap-east-1
None
```

## Environment details

* Affected module version: v5.1.0
* OS: any
* Terraform version: 0.12.7

## Any other relevant info
Perhaps there is different owner in HK region? https://github.com/awslabs/amazon-eks-ami/pull/305/files/fd9cf4458dffa1e9c01a3a42fca1cc7690abc504

**Comment by max-rocket-internet** [comment] 2019-08-26 10:53
> Perhaps there is different owner in HK region?

Looks like it. Strange.

**Comment by vranystepan** [comment] 2019-08-26 16:04
Internally we've applied temp. workaround in `data.tf`:

```hcl
...
owners = ["602401143452", "800184023465"]
...
```

but this is not the solution as 800184023465 does not contain images with relevant names :)

**Comment by bsakweson** [comment] 2019-09-18 13:01
I seem to be having the same issue in us-east-1. Here is what I am seeing?

```
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/eks.eks/data.tf line 19, in data "aws_ami" "eks_worker":
  19: data "aws_ami" "eks_worker" {
```

A pick at the code shows this:
```
data "aws_ami" "eks_worker" {
  filter {
    name   = "name"
    values = ["amazon-eks-node-${var.cluster_version}-${var.worker_ami_name_filter}"]
  }

  most_recent = true

  # Owner ID of AWS EKS team
  owners = ["602401143452"]
}
```

I did not add any additional filter.

affected version: `v6.0.0`

**Comment by bsakweson** [comment] 2019-09-18 13:58
It turns out my cluster version was incorrect. Cluster version should not contain minor release, it should be for example 1.14. See this [https://github.com/awslabs/amazon-eks-ami](link) and this for [https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html](link) for details.

**Comment by JayThomason** [comment] 2019-09-20 00:14
@bsakweson I had the same issue today when I tried upgrading to 1.14.6.

Maybe the docs/README could be updated to reflect that only the major version should be specified.

**Comment by barryib** [comment] 2019-09-20 13:16
@vranystepan - Does the @bsakweson's comment help you ?

**Comment by barryib** [comment] 2019-09-23 18:54
> @bsakweson I had the same issue today when I tried upgrading to 1.14.6.
> Maybe the docs/README could be updated to reflect that only the major version should be specified.

This should specified in the [AWS EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html). You must only provider major version for EKS cluster. AWS handle minor upgrades for you. You can send a PR for that https://github.com/awsdocs/amazon-eks-user-guide

@vranystepan I'm closing this issue. Feel free to re-open it if the provided "solution" doesn't work for you.

**Comment by hato221** [comment] 2019-10-05 07:24
@barryib the issue is not related to EKS version. If you check @vranystepan's `aws ec2 describe ...` command, you will see that he tried to search for any image which has the owner with ID `602401143452`. For Hong Kong (ap-east-1) region, you need to change owner ID to `800184023465` otherwise, your search will return empty results.

**Comment by barryib** [comment] 2020-10-06 08:44
@hato221 I opened this PR #1038 to address the default owner issue. Can you please, tell me if it solves your issue.

**Closed** 2020-10-06 12:26 UTC

**Comment by sysnasri** [comment] 2021-11-13 17:01
I have the same issue but it was about cluster_version variable which I have set it to 1.22 but it worked with 1.20
