### ISSUE TITLE
terraform-provider-aws_v3.52.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by davidcsi** [terraform-aws-modules/terraform-aws-eks#1512] opened 2021-08-05 00:33 UTC
## Description

aws plugin crashes when destroy a previosuly created plan. The applied plan was timing out when creating an EKS cluster's worker group with launch_templates because they wouldn't join the cluster.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
```
$ terraform -version
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Reproduction

no

yes

Create a vpc/rds/eks project, then try ro destroy it.

### Code Snippet to Reproduce
```
$ terraform destroy -auto-approve -var-file dev.vars.json
```

## Expected behavior
should destroy the resources

## Actual behavior
terraform crashes

### Terminal Output Screenshot(s)
```
$ terraform destroy -auto-approve -var-file dev.vars.json
module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["backend"] (deposed object e37b3e00): Refreshing state... [id=dev-cluster:dev-cluster-backend20210804223728629800000004]
module.eks.module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0]: Refreshing state... [id=arn:aws:iam::482565586674:policy/dev-cluster-elb-sl-role-creation20210804214659099700000001]
module.eks.module.eks.aws_iam_role.cluster[0]: Refreshing state... [id=dev-cluster20210804214659099900000002]
module.vpc.aws_vpc.vpc: Refreshing state... [id=vpc-08f128760450d8d78]
module.eks.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]: Refreshing state... [id=dev-cluster20210804214659099900000002-20210804214710325900000005]
module.eks.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0]: Refreshing state... [id=dev-cluster20210804214659099900000002-20210804214710312000000003]
module.eks.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]: Refreshing state... [id=dev-cluster20210804214659099900000002-20210804214710326700000006]
module.eks.module.eks.aws_iam_role_policy_attachment.cluster_elb_sl_role_creation[0]: Refreshing state... [id=dev-cluster20210804214659099900000002-20210804214710325800000004]
module.vpc.aws_route_table.private: Refreshing state... [id=rtb-08bbc2915b8343f60]
module.vpc.aws_subnet.public_subnet[1]: Refreshing state... [id=subnet-0596e269199531ebf]
module.vpc.aws_subnet.public_subnet[0]: Refreshing state... [id=subnet-0ec10fb5c521f31c3]
module.vpc.aws_security_group.default: Refreshing state... [id=sg-092d437293cb8d1e7]
module.vpc.aws_subnet.public_subnet[2]: Refreshing state... [id=subnet-06740809a8f2dbb40]
module.vpc.aws_internet_gateway.ig: Refreshing state... [id=igw-041b46a6d8c340141]
module.vpc.aws_subnet.private_subnet[2]: Refreshing state... [id=subnet-0016e60647545908a]
module.vpc.aws_subnet.private_subnet[1]: Refreshing state... [id=subnet-07ab1556eb805f44f]
module.vpc.aws_subnet.private_subnet[0]: Refreshing state... [id=subnet-07fbd0775f997de8e]
module.vpc.aws_route_table.public: Refreshing state... [id=rtb-0deccd3aa9e4c2467]
module.eks.aws_security_group.sg_ssh_mgmt: Refreshing state... [id=sg-073e2fd7f21521f34]
module.eks.aws_security_group.sg_sip_b2bua: Refreshing state... [id=sg-03a60be8c1f9ba31b]
module.eks.aws_security_group.sg_sip_proxy: Refreshing state... [id=sg-0dfe5d62984ef3bee]
module.eks.module.eks.aws_security_group.cluster[0]: Refreshing state... [id=sg-01e96395c9fd957fe]
module.eks.module.eks.aws_security_group.workers[0]: Refreshing state... [id=sg-0a4a33eb5abdb5f9b]
module.vpc.aws_eip.nat_eip: Refreshing state... [id=eipalloc-073ec19382d8723b2]
module.vpc.aws_route.public_internet_gateway: Refreshing state... [id=r-rtb-0deccd3aa9e4c24671080289494]
module.vpc.aws_route_table_association.private[1]: Refreshing state... [id=rtbassoc-08fa3f68b1d1b664c]
module.vpc.aws_route_table_association.private[2]: Refreshing state... [id=rtbassoc-099d0c0ae5e66ac44]
module.vpc.aws_route_table_association.private[0]: Refreshing state... [id=rtbassoc-0e31636401941d9ca]
module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-0b15cd6fb41ec070c]
module.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-0a5112979a6085e28]
module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-05538c151ed20e706]
module.eks.aws_launch_template.backend: Refreshing state... [id=lt-0348d36e56de61d27]
module.eks.aws_security_group_rule.sg_ssh_mgmt_rule: Refreshing state... [id=sgrule-3130381074]
module.eks.aws_security_group_rule.sg_sip_proxy_rule_udp: Refreshing state... [id=sgrule-3595462455]
module.eks.aws_security_group_rule.sg_sip_proxy_rule_tcp: Refreshing state... [id=sgrule-2827060655]
module.eks.aws_launch_template.sip-proxy: Refreshing state... [id=lt-0c85a795c4424bd08]
module.eks.aws_security_group_rule.sg_sip_b2bua_rule_signalling_tcp: Refreshing state... [id=sgrule-3718308495]
module.eks.aws_security_group_rule.sg_sip_b2bua_rtp_rule_udp: Refreshing state... [id=sgrule-720838854]
module.eks.aws_security_group_rule.sg_sip_b2bua_rule_signalling_udp: Refreshing state... [id=sgrule-2046771552]
module.eks.aws_security_group_rule.sg_sip_b2bua_rtp_rulet_tcp: Refreshing state... [id=sgrule-1413005918]
module.eks.aws_launch_template.sip-b2bua: Refreshing state... [id=lt-074a2d1092e5c3e33]
module.eks.module.eks.aws_security_group_rule.workers_ingress_cluster_https[0]: Refreshing state... [id=sgrule-196423424]
module.eks.module.eks.aws_security_group_rule.cluster_egress_internet[0]: Refreshing state... [id=sgrule-582182485]
module.eks.module.eks.aws_security_group_rule.workers_ingress_cluster[0]: Refreshing state... [id=sgrule-84029055]
module.eks.module.eks.aws_security_group_rule.workers_egress_internet[0]: Refreshing state... [id=sgrule-253635078]
module.eks.module.eks.aws_security_group_rule.workers_ingress_self[0]: Refreshing state... [id=sgrule-4275792234]
module.eks.module.eks.aws_security_group_rule.cluster_https_worker_ingress[0]: Refreshing state... [id=sgrule-2605205200]
module.vpc.aws_nat_gateway.nat: Refreshing state... [id=nat-026bfd76c4ca45f4a]
module.vpc.aws_route.private_nat_gateway: Refreshing state... [id=r-rtb-08bbc2915b8343f601080289494]
module.eks.module.eks.aws_eks_cluster.this[0]: Refreshing state... [id=dev-cluster]
module.eks.module.eks.aws_iam_role.workers[0]: Refreshing state... [id=dev-cluster2021080422001981820000000f]
module.eks.module.eks.local_file.kubeconfig[0]: Refreshing state... [id=3a9b7f960f9c6be3f89ec9f23a865bd443a207a0]
module.eks.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Refreshing state... [id=dev-cluster2021080422001981820000000f-20210804220038547100000010]
module.eks.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Refreshing state... [id=dev-cluster2021080422001981820000000f-20210804220038970900000011]
module.eks.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Refreshing state... [id=dev-cluster2021080422001981820000000f-20210804220048438800000012]
module.eks.module.eks.kubernetes_config_map.aws_auth[0]: Refreshing state... [id=kube-system/aws-auth]
module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["backend"]: Refreshing state... [id=dev-cluster:dev-cluster-backend20210804230908771200000007]
module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["sip-b2bua"]: Refreshing state... [id=dev-cluster:dev-cluster-sip-b2bua20210804230908771200000009]
module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["sip-proxy"]: Refreshing state... [id=dev-cluster:dev-cluster-sip-proxy2021080423090877130000000b]
module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["backend"] (deposed object e37b3e00): Refreshing state... [id=dev-cluster:dev-cluster-backend20210804223728629800000004]
╷
│ Error: Request cancelled
│ 
│   with module.eks.module.eks.aws_iam_role.workers[0],
│   on .terraform/modules/eks.eks/workers.tf line 451, in resource "aws_iam_role" "workers":
│  451: resource "aws_iam_role" "workers" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.eks.aws_launch_template.backend,
│   on ../../modules/eks/launch_template_backend.tf line 1, in resource "aws_launch_template" "backend":
│    1: resource "aws_launch_template" "backend" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.eks.aws_launch_template.sip-b2bua,
│   on ../../modules/eks/launch_template_sip_b2bua.tf line 1, in resource "aws_launch_template" "sip-b2bua":
│    1: resource "aws_launch_template" "sip-b2bua" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.eks.aws_launch_template.sip-proxy,
│   on ../../modules/eks/launch_template_sip_proxy.tf line 1, in resource "aws_launch_template" "sip-proxy":
│    1: resource "aws_launch_template" "sip-proxy" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["backend"],
│   on .terraform/modules/eks.eks/modules/node_groups/node_groups.tf line 1, in resource "aws_eks_node_group" "workers":
│    1: resource "aws_eks_node_group" "workers" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v3.52.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 41 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEksNodeGroupRead(0x8a62898, 0xc00034d1a0, 0xc000354880, 0x0, 0x0, 0xc0022393d0, 0xc0022f3908, 0x100df38)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_eks_node_group.go:342 +0x1e6e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00093db20, 0x8a62828, 0xc000344a80, 0xc000354880, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00093db20, 0x8a62828, 0xc000344a80, 0xc00221c150, 0x0, 0x0, 0xc0003606c8, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c648, 0x8a62828, 0xc000344a80, 0xc000344ac0, 0xc000344a80, 0x100b665, 0x79e29a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc002400020, 0x8a628d0, 0xc000344a80, 0xc00034c9c0, 0xc002400020, 0xc001ebda70, 0xc002419ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7cc0b80, 0xc002400020, 0x8a628d0, 0xc001ebda70, 0xc00034c960, 0x0, 0x8a628d0, 0xc001ebda70, 0xc000353400, 0x4b7)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022fa40, 0x8a84a98, 0xc0015a7680, 0xc001eec100, 0xc000ffc630, 0xc2eb2b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022fa40, 0x8a84a98, 0xc0015a7680, 0xc001eec100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000052910, 0xc00022fa40, 0x8a84a98, 0xc0015a7680, 0xc001eec100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.52.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by daroga0002** [comment] 2021-08-25 08:43
how this is specifically related to this module?

**Comment by antonbabenko** [comment] 2021-08-25 15:16
Hi @davidcsi !

As @daroga0002 said the issue is not related to this module but to the [Terraform AWS provider](https://github.com/hashicorp/terraform-provider-aws).

Please open a bug report there.

I am going to close this issue here.

**Closed by antonbabenko** 2021-08-25 15:16 UTC
