### ISSUE TITLE
Create aws_autoscaling_group with for_each instead of count

### ISSUE THREAD

**Issue by jlewis42lines** [terraform-aws-modules/terraform-aws-eks#1007] opened 2020-09-10 21:46 UTC
## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently `worker_groups` is a list of maps, and is [expanded with count](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L4). This makes it impossible to remove ASGs which are not at the end of the list.

## What's the ~expected~ desired behavior?
I'd like to have aws_autoscaling_group resources created with `for_each` as is done in the [node_groups module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf#L2). This will allow "named" worker groups so one can delete any ASG as needed.

## Are you able to fix this problem and submit a PR? Link here if you have already.
I do not have time to submit this PR right now, so if someone else can pick it up that would be great!

## Environment details

* Affected module version: 12.2.0
* OS: n/a
* Terraform version: n/a

**Comment by dpiddockcmp** [comment] 2020-09-11 07:24
Duplicate of #732

**Closed by dpiddockcmp** 2020-09-11 07:24 UTC
