### ISSUE TITLE
Error when using `cluster_id` output in other modules/actions

### ISSUE THREAD

**Issue by fubar** [terraform-aws-modules/terraform-aws-eks#275] opened 2019-02-11 20:44 UTC
# I have issues

using the `cluster_id` output in other modules/actions

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Consider this `test.sh` bash script:

```shell
#!/bin/bash
echo "{\"kubeconfig\":\"${1}\"}"
```

And these Terraform definitions:

```terraform
locals {
  eks_cluster_name = "foo-cluster"
}

module "foo-cluster" {
  cluster_name = "${local.eks_cluster_name}"
  // ...
}

data "external" "kube_config_test" {
  program = [
    "test.sh",
    "${module.foo-cluster.cluster_id}"
  ]
}
```

This results in this error:

```
Resource 'data.external.kube_config_test' does not have attribute 'result.kubeconfig' for variable 'data.external.kube_config_test.result.kubeconfig'
```

However, if I reference the local variable, it works fine:

```terraform
data "external" "kube_config_test" {
  program = [
    "test.sh",
    "${local.eks_cluster_name}"
  ]
}
```

The script works fine; I've validated its output and it returns the expected string `{"kubeconfig":"foo-cluster"}` in both scenarios, but for some reason Terraform throws an error when using `module.foo-cluster.cluster_id`.

What's failing here?

## Environment details

Mac OS 10.13

Terraform and module versions:
```
* provider.aws: version = "~> 1.57"
* provider.external: version = "~> 1.0"
* provider.kubernetes: version = "~> 1.5"
* provider.local: version = "~> 1.1"
* provider.null: version = "~> 2.0"
* provider.random: version = "~> 2.0"
* provider.template: version = "~> 2.0"
```

**Comment by fubar** [comment] 2019-02-11 20:48
Another example of this issue:

```terraform
provider "kubernetes" {
  config_path = "${path.cwd}/kubeconfig_${module.foo-cluster.cluster_id}"
}
```

Throws:

```
module.foo.provider.kubernetes: Failed to load config (; default context): invalid configuration: no configuration has been provided
```

However, this works fine:

```terraform
provider "kubernetes" {
  config_path = "${path.cwd}/kubeconfig_${local.eks_cluster_name}"
}
```

**Comment by skang0601** [comment] 2019-03-07 13:53
I don't think the issue is with this module itself but rather the provider or terraform. This issue seems relevant: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/142

**Comment by max-rocket-internet** [comment] 2019-05-07 15:32
Closing after no update in a long time. Feel free to reopen 🙂

**Closed by max-rocket-internet** 2019-05-07 15:32 UTC
