### ISSUE TITLE
Release 7.0.1 missing node_groups.tf

### ISSUE THREAD

**Issue by brylex418** [terraform-aws-modules/terraform-aws-eks#656] opened 2020-01-02 20:34 UTC
# I have issues
Trying to use release 7.0.1 and nodegroups, however release is missing node_groups.tf
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment] 2020-01-03 09:29
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/628

**Closed by max-rocket-internet** 2020-01-03 09:29 UTC
