### ISSUE TITLE
Deprecation warning when installing EKS Add-ons

### ISSUE THREAD

**Issue by rljohnsn** [terraform-aws-modules/terraform-aws-eks#2814] opened 2023-11-10 18:59 UTC
## Description

Not really a bug but a deprecation warning

```
 Warning: Argument is deprecated
│
│   with module.eks.aws_eks_addon.this["kube-proxy"],
│   on .terraform/modules/eks/main.tf line 392, in resource "aws_eks_addon" "this":
│  392:   resolve_conflicts        = try(each.value.resolve_conflicts, "OVERWRITE")
│
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial
│ resource creation. Use "resolve_conflicts_on_create" and/or
│ "resolve_conflicts_on_update" instead
│
│ (and 3 more similar warnings elsewhere)
╵

```
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v19.19.0

- Terraform version:
```
terraform -version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.24.0

```
- Provider version(s):

```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.24.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

```
## Reproduction Code [Required]

```
module "eks" {
  source = "git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v19.19.0"

  cluster_name                   = "${local.env}-${local.name}"
  cluster_version                = local.cluster_version

  cluster_addons = {
    kube-proxy = {
      most_recent = true
    }
  }
}
```

## Expected behavior

Install the add-on

## Actual behavior

Add-on successfully installed. With Deprecation warning

### Terminal Output Screenshot(s)

see above

**Comment by bryantbiggs** [comment] 2023-11-10 19:10
Duplicate of #2635 

Yes, its unfortunate that Terraform doesn't provide a way to silence warnings. However, this will be resolved soon with the next version (v20) of the module

**Closed by bryantbiggs** 2023-11-10 19:10 UTC
