### ISSUE TITLE
eks module created IAM role doesn't have the correct policy

### ISSUE THREAD

**Issue by samsond** [terraform-aws-modules/terraform-aws-eks#2057] opened 2022-05-03 20:51 UTC
## Description

When creating EKS Cluster without providing an `aws_iam_role` cluster provisioning failed with the following error.

```
RespMetadata: {
│     StatusCode: 400,
│     RequestID: "85bda7f1-5954-4511-adsdsdsdsdffbd0"
│   },
│   ClusterName: "demo-cluster",
│   Message_: "Role with arn: arn:aws:iam::XXXXXXXX:role/demo-cluster-cluster-20220502180809034800000004, could not be assumed because it does not exist or the trusted entity is not correct"
│ }
│ 
│   with module.eks-cluster.aws_eks_cluster.this[0],
│   on .terraform/modules/eks-cluster/[main.tf](http://main.tf/) line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" {

```

I checked the IAM role mentioned above in the AWS console, the role is present. Looks like it is missing the required policy to pass role.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version: 18.20.5

- Terraform version: v1.0.8 on darwin_amd64

- Provider version(s):

```
provider [registry.terraform.io/hashicorp/aws](http://registry.terraform.io/hashicorp/aws) v4.12.1
provider [registry.terraform.io/hashicorp/cloudinit](http://registry.terraform.io/hashicorp/cloudinit) v2.2.0
provider [registry.terraform.io/hashicorp/kubernetes](http://registry.terraform.io/hashicorp/kubernetes) v2.11.0
provider [registry.terraform.io/hashicorp/tls](http://registry.terraform.io/hashicorp/tls) v3.3.0

```

## Reproduction Code [Required]

1.  create test code as below
2. `terraform init`
3. `terraform plan`
4. `terraform apply`
 

### Code Snippet to Reproduce

```
provider "aws" {
  region = "us-west-2"
}

terraform {
  required_version = "1.0.8"

  backend "s3" {
    bucket = "XXX-example"
    key    = "XXXX-tf-state"
    region = "us-west-2"
  }
}



module "eks-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  version      = "18.20.5"
  cluster_name = "demo-cluster"
  cluster_version = "1.21"
  subnet_ids     = ["subnet-XXXXXXX", "subnet-XXXXX", "subnet-XXXXX"]
  vpc_id       = "vpc-XXXXX"

 eks_managed_node_groups = {
    blue = {}
    green = {
      min_size     = 1
      max_size     = 1
      desired_size = 1

      instance_types = ["t3.large"]
    }
  }

  eks_managed_node_group_defaults = {
    disk_size      = 50
    instance_types = ["t3.large", "m5n.large", "m5zn.large"]
  }


  tags = {
    environment = "demo"
  }
}
```

## Expected behavior

EKS Cluster IAM role created with a correct policy.

## Actual behavior

EKS Cluster creation failed because of not getting the correct policy.

**Comment by bryantbiggs** [comment] 2022-05-03 20:55
Hi @samsond - we need a reproduction that is deployable to troubleshoot

**Comment by samsond** [comment] 2022-05-03 21:16
@bryantbiggs The code I share under code snippet to reproduce is the code I have used.

**Comment by bryantbiggs** [comment] 2022-05-03 21:20
@samsond I cannot deploy this with `XXXX`
```hcl
module "eks-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  version      = "18.20.5"
  cluster_name = "demo-cluster"
  cluster_version = "1.21"
  subnet_ids     = ["subnet-XXXXXXX", "subnet-XXXXX", "subnet-XXXXX"]
  vpc_id       = "vpc-XXXXX"
  ...
```

**Comment by samsond** [comment] 2022-05-03 21:30
@bryantbiggs I cannot provide the AWS resources, you can just simply use any subnet and vpc if you have AWS account.

**Comment by bryantbiggs** [comment] 2022-05-03 22:17
Closing out due to unable to reproduce issue. 

Configuration that was used to validate and deployed successfully:
```hcl
locals {
  name   = "demo-cluster"
  region = "us-east-1"

  tags = {
    environment = "demo"
  }
}

module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  version      = "18.20.5"

  cluster_name = local.name
  cluster_version = "1.21"

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

 eks_managed_node_groups = {
    blue = {}
    green = {
      min_size     = 1
      max_size     = 1
      desired_size = 1

      instance_types = ["t3.large"]
    }
  }

  eks_managed_node_group_defaults = {
    disk_size      = 50
    instance_types = ["t3.large", "m5n.large", "m5zn.large"]
  }

  tags = {
    environment = "demo"
  }
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = local.name
  cidr = "10.0.0.0/16"

  azs             = ["${local.region}a", "${local.region}b", "${local.region}c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/elb"              = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/internal-elb"     = 1
  }

  tags = local.tags
}
```

**Closed by bryantbiggs** 2022-05-03 22:17 UTC
Labels: needs update

**Comment by kimxogus** [comment] 2022-05-20 03:35
I'm having the same problem.

**Comment by ajpauwels** [comment] 2022-07-20 09:15
I am having the exact same problem, have been debugging for three days to no avail. Running the cluster update command using the aws CLI leads to the same error. The role most definitely exists and has a trust relationship to allow EKS to assume it.
