### ISSUE TITLE
LaunchTemplate creation can fail when metadata_options supplied

### ISSUE THREAD

**Issue by philicious** [terraform-aws-modules/terraform-aws-eks#1831] opened 2022-02-02 15:54 UTC
## Description

LT creation fails in combination with `metadata_options` config

## Versions

 - Terraform: 1.1.x

 - Provider(s): hashicorp/aws v3.73.0

 - Module: 18.2.1

## Reproduction
I had a MNG with LT that had in `eks_managed_node_group_defaults` metadata_options set up and running just fine
```
eks_managed_node_group_defaults {
    metadata_options = {
      http_tokens = "optional" // keep support for IMDSv1
    }
}
```

I then removed the MNG and wanted to add a new MNG, however to my surprise I then got reproducible error 
```
╷
│ Error: InvalidParameterValue: A value of ‘’ is not valid for http-endpoint. Valid values are ‘enabled’ or ‘disabled’.
│ 	status code: 400, request id: e126b5f6-a1f9-4666-9e4f-c84981b8e5cf
│
│   with module.eks.module.eks.module.eks_managed_node_group["new_group"].aws_launch_template.this[0],
│   on .terraform/modules/eks.eks/modules/eks-managed-node-group/main.tf line 37, in resource "aws_launch_template" "this":
│   37: resource "aws_launch_template" "this" {
│
```

I could easily fix it by adding to the metadata_options `http_endpoint = "enabled"` . However this shouldnt be necessary regularly.

```
eks_managed_node_group_defaults {
    metadata_options = {
      http_tokens = "optional" // keep support for IMDSv1
      http_endpoint = "enabled"
    }
}
```

Somehow an edge-case, still tracking it here for what its worth

**Comment by bryantbiggs** [comment] 2022-02-02 16:02
needs reproduction config

**Comment by philicious** [comment] 2022-02-03 11:21
@bryantbiggs should I provide a full-working gist ?  as for reproduction my supplied code would suffice as its the relevant part of config

**Comment by bryantbiggs** [comment] 2022-02-15 21:49
related upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/23174

**Comment by philicious** [comment] 2022-02-15 22:15
@bryantbiggs reading the upstream issue, I can confirm it's actually that. 
I encountered it a second time in a bit different scenario that matches upstream issue more closely than this here. 

Feel free to close here then. Thanks for keeping overview :)

**Comment by bryantbiggs** [comment] 2022-02-16 12:40
it looks like they have a fix and there won't be any required change here so closing for now https://github.com/hashicorp/terraform-provider-aws/pull/23213

**Closed by bryantbiggs** 2022-02-16 12:40 UTC
Labels: upstream blocker
