### ISSUE TITLE
create_elb_service_linked_role expects an integer and not a bool

### ISSUE THREAD

**Issue by zknill** [terraform-aws-modules/terraform-aws-eks#124] opened 2018-09-10 12:04 UTC
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behaviour?
`create_elb_service_linked_role` expects an integer, and not a boolean as described in the docs.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0180644770878a28bc9511b7a0ce285c0e7454db/README.md#L105

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Instantiate the module with:
```hcl

module "eks" {
  // trimmed ...

   create_elb_service_linked_role = "true"
}
```
And run `terraform plan`:
```
Error: Error refreshing state: 1 error(s) occurred:

* module.infrastructure.module.eks.aws_iam_service_linked_role.elasticloadbalancing: cannot parse "true" as an integer
```

This appears to be because `create_elb_service_linked_role` is used directly as the `count` field.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/405e170f90a6b0ac0ef9b1e63e622996bf28dabe/cluster.tf#L62-L64

## What's the expected behavior?

Expect to be able to pass `create_elb_service_linked_role = "true"` instead of `create_elb_service_linked_role = 1`. The former is the usage described in `README.md` file

## Are you able to fix this problem and submit a PR? Link here if you have already.

Very happy to make a PR; I believe it's a simple update of:

```hcl
count = "${var.create_elb_service_linked_role == "true" ? 1 : 0}"
```

## Environment details

* Affected module version: `1.6.0`
* OS: `Linux`
* Terraform version: `v0.11.6`

**Comment by max-rocket-internet** [comment] 2018-09-10 12:08
Can you set `create_elb_service_linked_role = true`, without the quotes and it works?

**Comment by max-rocket-internet** [comment] 2018-09-10 13:09
I see. So do you think it's it a bug or a documentation issue?

**Comment by Jeeppler** [comment] 2018-09-10 15:49
@max-rocket-internet yes, it is a documentation issue.

**Comment by max-rocket-internet** [comment] 2018-09-11 07:35
But it's documented the same way as all the other `true`/`false` variables in the README, right? Are you saying they should all be documented differently?

**Comment by Jeeppler** [comment] 2018-09-12 17:34
@max-rocket-internet the confusing part in the README is the `string` type hint:

```
 | create_elb_service_linked_role | Whether to create the service linked role for the elasticloadbalancing service. Without this EKS cannot create ELBs. | string | `false` | no | 
```
A change from `string` to `bool` would be enough and maybe include `create_elb_service_linked_role = true` in one of the examples in the README.

**Comment by email2liyang** [comment] 2018-09-12 20:45
what's required to make eks to be able to create elb if you set create_elb_service_linked_role=true, from what I understand is that it just apply these lines

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/405e170f90a6b0ac0ef9b1e63e622996bf28dabe/cluster.tf#L62-L65

and it will create Service role name AWSServiceRoleForElasticLoadBalancing .

but what I experienced is that if I apply ingress-nginx from https://github.com/kubernetes/ingress-nginx/blob/master/docs/deploy/index.md. 

the external ip will always be <pending>

```
kubectl get svc -n ingress-nginx
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default-http-backend   ClusterIP      172.20.89.251   <none>        80/TCP                       34m
ingress-nginx          LoadBalancer   172.20.91.131   <pending>     80:30537/TCP,443:30088/TCP   32m
```

**Comment by email2liyang** [comment] 2018-09-12 22:02
I finally get what's going on. if we also provision the vpc by terraform vpc module, we must add tag to the public sub net which is used by eks to create ELB
the tag format should be
```
 kubernetes.io/cluster/<eks-cluster-name> = shared 
```

then when you create LoadBalancer type of service , it can create ELB based for public subnet which has tag  kubernetes.io/cluster/<eks-cluster-name> = shared

**Comment by Jeeppler** [comment] 2018-09-12 23:01
@email2liyang You are right. This would look like this:

```
  vpc_tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
  }

  public_subnet_tags = {
    Subnet = "public"

    # this is a workaround for the case in which terraform is run twice.
    # Otherwise Terraform will remove those tags.
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
  }

  private_subnet_tags = {
    Subnet = "private"

    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
  }
```

However, this only happens if you run `terraform apply` twice. The issue is that, when you run it the second time terraform tries to remove the `"kubernetes.io/cluster/<your-cluster-name>" = "shared"` tag.

**Comment by email2liyang** [comment] 2018-09-13 02:11
yes, same, here, you should manage the tag in vpc module rather than eks module.

and I don't think we need to apply  "kubernetes.io/cluster/${var.cluster_name}" = "shared" to private subnet, as private subnet can't create ELB

**Comment by max-rocket-internet** [comment] 2018-09-13 08:27
We are talking about a few issues here.

1. Documentation 

> A change from string to bool would be enough and maybe include 

Yeah, I get you and I agree but the doc is automatically generated using `terraform-docs`. All "booleans" are treated and documented in the same way. I think it would be good to change this.

2. K8s choosing subnets for ELBs. You've already worked out the tagging.

3. Issue with `aws_iam_service_linked_role`. Is there any issue here? There's a couple of related issues https://github.com/terraform-aws-modules/terraform-aws-eks/issues/120 https://github.com/terraform-aws-modules/terraform-aws-eks/issues/132 so this seems to be a pain point. I'm not sure what the solution is.

**Comment by email2liyang** [comment] 2018-09-13 14:47
for this var  setting "create_elb_service_linked_role" it will apply these lines https://github.com/terraform-aws-modules/terraform-aws-eks/blob/405e170f90a6b0ac0ef9b1e63e622996bf28dabe/cluster.tf#L62-L65.

and it will create Service role named AWSServiceRoleForElasticLoadBalancing. but if it's already exist, the terraform apply will failed, this happens to at least 2 of my aws account, but the eks cluster has been created successfully.

is there way to detect if AWSServiceRoleForElasticLoadBalancing has already created in the underling aws account to avoid the duplication error?

Thanks

**Comment by zknill** [comment] 2018-09-14 13:45
On `1.` I agree it's confusing docs that led me to open the issue.

IMO it would be better if the variable type here was `bool`:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0180644770878a28bc9511b7a0ce285c0e7454db/README.md#L105

**Comment by max-rocket-internet** [comment] 2018-09-18 08:52
I agree about the labelling of `bool` types but I think this will all change in TF version 0.12.

I am going to close this issue as it's not really about `create_elb_service_linked_role` parameter, it's about how all parameters are labelled. And this is generated from `terraform-docs`.

For now the options are:
1. Wait until TF 0.12 as this has a lot of type changes and handling.
2. Create a new issue with a proposal to change `terraform-docs` to something else. Or stop using it.

**Closed by max-rocket-internet** 2018-09-18 08:52 UTC

**Comment by Jeeppler** [comment] 2018-09-18 20:36
@max-rocket-internet How about adding this parameter in one of the examples in Terraform module description. That should be possible right now, without waiting for TF version 0.12.
