### ISSUE TITLE
tls: failed to verify certificate: x509: “kube-apiserver” certificate is not trusted

### ISSUE THREAD

**Issue by ptravishill** [terraform-aws-modules/terraform-aws-eks#2791] opened 2023-10-23 16:00 UTC
## Description

The issue is pertinent to an EKS cluster that has been managed by terraform-aws-eks and maintained by it for quite some time. Recently, I started running into the following error when running my Terraform Cloud EKS pipeline via remote managed workflow:

```
│ Error: Get "https://<REDACTED>.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": tls: certificate signed by unknown authority
│
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 554, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  554: resource "kubernetes_config_map_v1_data" "aws_auth" {
```

This error only occurs when terraform detects a change and needs to authenticate to the kube-apiserver to change something inside the cluster.

If I switch the terraform cloud pipeline to local execution, the error remains but it changes slightly:

```
│ Error: Get "https://<REDACTED>.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": tls: failed to verify certificate: x509: “kube-apiserver” certificate is not trusted
│
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 554, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  554: resource "kubernetes_config_map_v1_data" "aws_auth" {
```

I have switched between remote and local executions. I have ran terraform refreshes remotely and locally to reauth expired auth tokens. I have redownloaded cluster config via awscli and retried. Nothing I have tried has worked. Any help would be appreciated. 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

- [X] ✋ Done. Issue still persists. 

## Versions

- AWS EKS Kubernets Version
`v1.28`

- Module version [Required]:
`v19.17.2`

- Terraform version:
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.22.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/viktorradnai/bcrypt v0.1.2
```

## Reproduction Code [Required]

Here is my code:
```
terraform {
  cloud {
    organization = "<REDACTED>"
    workspaces {
      name = "<REDACTED>"
    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.20.0"
    }
...

  required_version = ">= 0.14"
}

provider "aws" {
  region = var.region
  default_tags {
    tags = {
      Purpose     = var.purpose
      Project     = var.project_name
      Environment = var.environment
      Owner       = var.owner
    }
  }
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
...
```

I can give more main.tf code, but its quite lengthy. 

## Expected behavior

Terraform runs and is able to communicate to the kube-apiserver in EKS without issue.  

## Actual behavior

Terraform errors with a certificate error contacting the kube-apiserver in EKS.

**Comment by ptravishill** [comment] 2023-10-23 18:20
To add further information to this. If I use my code to change the aws auth config, it works fine. And can change it in kubernetes. But, when I change something else that isn't even specific to resources inside the cluster but resources in AWS, it throws the error. 

For instance, if I try to attach a security group in the eks module, it will throw then same error.

**Comment by bryantbiggs** [comment] 2023-11-14 15:24
I suspect this is related to your local setup and usage in terms of how you connect and authenticate with the control plane. closing since the issue is not reproducible for us

**Closed by bryantbiggs** 2023-11-14 15:24 UTC
Labels: question
