### ISSUE TITLE
uncontrollable diff `platform_version` happens when executing a terraform plan/apply

### ISSUE THREAD

**Issue by hgsgtk** [terraform-aws-modules/terraform-aws-eks#2909] opened 2024-02-07 04:59 UTC
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

When I applied a change in my terraform project, I got the below message.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply".
which may have affected this plan:

  # {resource_name} has changed
  ~ resource "aws_eks_cluster" "this" {
        id                        = "{id}"
        name                      = "{id}"
      ~ platform_version          = "eks.x" -> "eks.x"

        # (10 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }
```

The diff doesn't contain any diff about the resource. The trigger is the EKS kubernetes engine upgrade, but I didn't expect the diff and actually I had no control to handle this notion because there is no API to specify either the platform version or the ignore life_cycle.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:20.2.0 (latest)

- Terraform version: v1.3.2

- Provider version(s):

```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.1
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.0"

  cluster_name    = local.cluster_name
  cluster_version = var.kubernetes_version

  cluster_endpoint_public_access = true
  create_kms_key                 = false

...

}
```

Steps to reproduce the behavior: Create a EKS cluster, conduct a kubernetes version upgrade, and execute a terraform plan

## Expected behavior

- No diff on terraform plan
- Either provide an option to specify the platform version or set the attribute as ignorable.

Specifically, the resource `aws_eks_cluster` might need to define the platform attribute explicitly.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a9212a423fc9e2959ac179c72a3c31bb5826e567/main.tf#L58
- platform attribute: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#platform_version

## Actual behavior

- Unwanted diff.

**Comment by hgsgtk** [comment] 2024-02-07 05:57
I realized that similar symptom happened when EKS addons were upgraded.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply"
which may have affected this plan:

  # xxx.this["aws-ebs-csi-driver"] has changed
  ~ resource "aws_eks_addon" "this" {
        id                   = "{id}"
      ~ modified_at       = "2023-12-19T03:26:49Z" -> "2024-02-06T02:12:21Z"
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # xxx.this["kube-proxy"] has changed
  ~ resource "aws_eks_addon" "this" {
        id                   = "{id}"
      ~ modified_at       = "2023-12-19T03:21:57Z" -> "2024-02-06T02:15:46Z"

        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # xxx.this["vpc-cni"] has changed
  ~ resource "aws_eks_addon" "this" {
        id                   = "{id}"
      ~ modified_at          = "2023-12-19T03:26:29Z" -> "2024-02-06T02:21:13Z"

        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

I wonder which layer is involved in this behavior, terraform, terraform-aws-provider, or terraform-aws-eks.

**Comment by bryantbiggs** [comment] 2024-02-08 00:08
this looks like you are using an output that has all of these values, but hard to tell since there isn't a full reproduction. However, there isn't anything related to the module here so closing this issue for now

**Closed by bryantbiggs** 2024-02-08 00:08 UTC
