### ISSUE TITLE
Setup kubeconfig without running kubectl under local exec

### ISSUE THREAD

**Issue by sumitag** [terraform-aws-modules/terraform-aws-eks#447] opened 2019-07-26 14:18 UTC
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Adding an additional role to the EKS cluster requires kubectl in local exec. We would like this to work natively in Terraform.

## What's the expected behavior?

Terraform supports making kubeconfig change natively and it would be great to support that in this module. Detailed here:
https://medium.com/@alex.veprik/setting-up-aws-eks-cluster-entirely-with-terraform-e90f50ab7387

## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/sumitag/terraform-aws-eks/pull/new/v4.0.2_native_Terraform

I don't think this keeps all the functionality working

## Environment details

* Affected module version: v4.0.2
* OS:
* Terraform version: 0.11

**Comment by max-rocket-internet** [comment] 2019-07-30 13:09
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/353

**Closed by max-rocket-internet** 2019-07-30 13:09 UTC
