### ISSUE TITLE
Audit CloudWatch Log Group settings do not take effect

### ISSUE THREAD

**Issue by sidewinder12s** [terraform-aws-modules/terraform-aws-eks#2365] opened 2022-12-22 18:39 UTC
## Description

It looks like because there isn't a depends on between this log group and the EKS cluster, EKS is likely creating the log group before the module. The EKS cluster resource explicitly calls this out: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabling-control-plane-logging

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v18.29.1

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/http v3.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

## Reproduction Code [Required]

```hcl
  cloudwatch_log_group_retention_in_days = 30
  cluster_enabled_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
```

Use the module with Audit logs enabled, tags set, audit log retention set.

## Expected behavior

CloudWatch Log retention set, tags set

## Actual behavior

No log retention set, no tags set

**Comment by bryantbiggs** [comment] 2023-01-05 17:40
the log group is created long before the cluster (cluster takes roughly 12 minutes to create). closing due to lack of reproduction

**Closed by bryantbiggs** 2023-01-05 17:40 UTC
