### ISSUE TITLE
sub module "eks_managed_node_group" ignores "bootstrap_extra_args"

### ISSUE THREAD

**Issue by youwalther65** [terraform-aws-modules/terraform-aws-eks#1823] opened 2022-02-01 08:59 UTC
## Description

I followed the "complete" example from:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L180
I use EKS sub module "eks_managed_node_group" with custom AMI and bootstrap extra args. These settings are ignored and MNG uses standard bootstrap settings.

## Versions

 - Terraform:  v1.1.4

 - Provider(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

 - Module: AWS EKS 18.2.4

### Code Snippet to Reproduce
data "aws_ami" "al2_ami" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amazon-eks-node-${local.cluster_version}-*"]
  }
}

module "eks_managed_node_group" {
  source = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "~> 18.0"
...
  ami_id                     = data.aws_ami.al2_ami.id
  enable_bootstrap_user_data = true
  bootstrap_extra_args       = "--container-runtime containerd --kubelet-extra-args '--max-pods=5'"

  pre_bootstrap_user_data = <<-EOT
    export CONTAINER_RUNTIME="containerd"
    export USE_MAX_PODS=false
  EOT
...
}

## Expected behavior
containerd is used as CRE and maxpods are set for kubelet

## Actual behavior
Default bootstrap settings are used including Docker as CRE

**Comment by bryantbiggs** [comment] 2022-02-01 13:19
duplicate of #1770 

see this comment https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1770#issuecomment-1014644200
and related upstream issue and response https://github.com/awslabs/amazon-eks-ami/issues/844

**Closed by bryantbiggs** 2022-02-01 13:19 UTC
