### ISSUE TITLE
Adding a new worker group to worker_group can cause existing worker_groups to be recreated

### ISSUE THREAD

**Issue by crhuber** [terraform-aws-modules/terraform-aws-eks#773] opened 2020-03-10 17:05 UTC
# I have issues
Adding a new worker group to the top of the array `worker_groups_launch_template` will cause group1 to be deleted and recreated and potentially causing an outage when group1 gets deleted/recreated.

When you have multiple groups in the array it is not always apparent that the lower items in the array will be recreated. 

It would be preferable to have the module use "map/foreach" for `worker_groups_launch_template` instead of an array , to avoid unnecessary/accidental recreation

```
  worker_groups_launch_template = [
    {
    name = "group1"
    },
]
```
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

worker_groups_launch_template is an array

## What's the expected behavior?

Being able to add a new group anywhere in  worker_groups_launch_template and not have the order matter 

## Environment details

* Affected module version:  "v6.0.1"
* OS: MacOS
* Terraform version:
Terraform v0.12.21

**Comment by max-rocket-internet** [comment] 2020-03-11 16:27
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/732

**Closed by max-rocket-internet** 2020-03-11 16:27 UTC
