### ISSUE TITLE
aws_eks_addon resolve_conflicts attribute is depricated

### ISSUE THREAD

**Issue by rpuserh** [terraform-aws-modules/terraform-aws-eks#2657] opened 2023-06-21 03:04 UTC
See terraform deprecated attribute when enabling addons 

```
│ Warning: Argument is deprecated
│
│   with module.eks.aws_eks_addon.this["kube-proxy"],
│   on .terraform/modules/eks/main.tf line 392, in resource "aws_eks_addon" "this":
│  392:   resolve_conflicts        = try(each.value.resolve_conflicts, "OVERWRITE")
│
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or "resolve_conflicts_on_update" instead
│
│ (and 3 more similar warnings elsewhere)
```

**Comment by bryantbiggs** [comment] 2023-06-21 03:30
Duplicate of #2635

**Closed** 2023-06-21 03:30 UTC
