### ISSUE TITLE
Your query returned no results, eks_worker_windows"

### ISSUE THREAD

**Issue by rajeshwarponugoti** [terraform-aws-modules/terraform-aws-eks#2538] opened 2023-03-28 14:17 UTC
## Description

I got an error while running jenkins job
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/eks/data.tf line 36, in data "aws_ami" "eks_worker_windows":
  36: data "aws_ami" "eks_worker_windows" {

I am using this variables already for us-east-1 region

variable "worker_ami_owner_id" { default = "602401143452" }
variable "worker_ami_owner_id_windows" { default = "amazon" }

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

terraform {
  required_version = ">= 0.12.9"
  # required_version = ">= 0.13.1"
  backend "s3" {}
}

provider "aws" {
  # Note: keep at version 2.47.0, as 2.48.0 looks to have a breaking change with the kubernetes module.
  version = "2.47.0"
  region  = var.aws_region
  # source  = "hashicorp/aws"
  # version = ">= 3.40.0"
}

provider "random" {
  version = "~> 2.1"
}

provider "local" {
  version = "~> 1.2"  #1.2 was there
}

provider "null" {
  version = "~> 2.1"
}

provider "template" {
  version = "~> 2.1"
}
## Actual behavior

Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/eks/data.tf line 36, in data "aws_ami" "eks_worker_windows":
  36: data "aws_ami" "eks_worker_windows" {

**Comment by bryantbiggs** [comment] 2023-05-17 13:35
closing due to lack of reproduction - this modules current version does not support windows AMIs

**Closed by bryantbiggs** 2023-05-17 13:35 UTC
Labels: question
