### ISSUE TITLE
Error: Failed to download module

### ISSUE THREAD

**Issue by nxf5025** [terraform-aws-modules/terraform-aws-eks#672] opened 2020-01-09 19:45 UTC
# I have issues
Unable to download the module. This was working earlier in the day. Anyone else hitting this?
```
Initializing modules...
Downloading terraform-aws-modules/eks/aws 7.0.1 for eks...

Error: Failed to download module

Could not download module "eks" (eks-cluster.tf:110) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/tarball/v7.0.1//*?archive=tar.gz":
Error opening a gzip reader for /tmp/getter059103677/archive: EOF.


Error: Failed to download module

Could not download module "eks" (eks-cluster.tf:110) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/tarball/v7.0.1//*?archive=tar.gz":
Error opening a gzip reader for /tmp/getter059103677/archive: EOF.
```
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
See above

## Environment details

* Affected module version: 7.0.1, but also tried 8.0.0 with same issue
* OS:
* Terraform version: 0.12.6

**Comment by Ghazgkull** [comment] 2020-01-09 19:52
Yes, we've just started seeing the same issue.

**Comment by mpeamma** [comment] 2020-01-09 20:00
I am seeing this issue as well

**Comment by leandroandrade-hotmart** [comment] 2020-01-09 20:20
Try to update to Terraform v0.12.19

**Comment by jemc** [comment] 2020-01-09 20:46
I hit the same issue; was on Terraform v0.12.13.
Terraform v0.12.19 works for me.

**Comment by jemc** [comment] 2020-01-09 21:01
Is there any explanation of how this was able to break?

Why is it that a locked Terraform version (`v0.12.13`) and a locked module version (`7.0.1`) wasn't sufficient to protect the reproducibility of my build? What changed?

**Comment by barryib** [comment] 2020-01-09 21:08
Here are required versions for Terraform and providers https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf

Here what changed https://github.com/terraform-aws-modules/terraform-aws-eks/pull/617.

Closing this issue. Feel free to re-open it if needed.

**Comment by kkapoor1987** [comment] 2020-01-09 21:14
@barryib We are trying to download 6.0.2 version of module and failing with same error

**Comment by jemc** [comment] 2020-01-09 21:15
@barryib - Sorry, that doesn't satisfy - did you read my comment above that this module is broken with Terraform `v0.12.13`?

The link in your comment says that `>v0.12.9` is required but that means my invocation with `v0.12.13` should work, *and it doesn't*.

**Comment by nxf5025** [comment] 2020-01-09 21:21
@barryib - To add on to what @jemc pointed out v7.01 has the following required versions: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v7.0.1/versions.tf

Also it seems #617 was a result of the managed node groups which wasn't even a part of the v7.0.1 release.

**Comment by jemc** [comment] 2020-01-09 21:22
Additionally, please note the other context from my comment - this same combination of Terraform version (`v0.12.13`) and module version (`7.0.1`) was working in our CI/CD pipeline *earlier today*, and for *weeks prior*.

My comment asking about what could have changed is holding in constant the two ostensibly immutable artifacts of terraform version and module version.

**Comment by JulianGindi** [comment] 2020-01-09 21:33
I have the same question as @jemc. We version our modules and this broke without any subsequent updates. 

> My comment asking about what could have changed is holding in constant the two ostensibly immutable artifacts of terraform version and module version.

How can we protect ourselves from this in the future?

**Comment by barryib** [comment] 2020-01-09 21:42
I answer it with this in mind **Terraform version: 0.12.6**.

Beside of that, I see that there is a bug fix in [Terraform 0.12.19](https://github.com/hashicorp/terraform/blob/v0.12.19/CHANGELOG.md) saying :

> command/init: Fix an issue with via an update to go-getter where modules would fail to download from the registry (#23792)

@jemc Is that satisfy you ?

**Comment by cloud-pharaoh** [comment] 2020-01-09 21:49
@barryib We weren't seeing the issue with 0.12.8 yesterday and just started happening today so instead of fix the issue in 0.12.9 I think it got broken further somehow.

**Comment by barryib** [comment] 2020-01-09 21:51
Please share your terraform scripts and output in debug mode.

**Comment by kkapoor1987** [comment] 2020-01-09 21:51
@barryib can we open the issuse. Its seems we are failing even for 0.12.16

**Comment by barryib** [comment] 2020-01-09 22:22
This is coming from Terraform core and the registry. Modules don't act in the `init` (service discovery, module downloading, backend initialization, etc.). All those operation are done by Terraform itself. If it works in some versions of Terraform, it should work for all of them or its a bug in Terraform side and from this module. https://www.terraform.io/docs/commands/init.html

Furthermore, the Terraform Registry is a Terraform repository maintained by Hashicorp. We only push tgz when we add git tags. https://www.terraform.io/docs/registry/modules/publish.html

**Closed** 2020-01-09 22:36 UTC

**Comment by harishrocky** [comment] 2020-11-28 15:41
hi All,

getting the same error;


Could not download module "vpc" (main.tf:11) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0': git
must be available and on the PATH.


i am using terraform v 0.13.5..Could you please help as I can't dowload any module not just this one,,

**Comment by lkwg82** [comment] 2021-11-09 17:38
> git must be available and on the PATH.

Install git and verify by running 'git --version'

**Comment by Nuxij** [comment] 2021-12-11 02:48
I am seeing this issue when using Terraform Cloud. What should I do?
