### ISSUE TITLE
Document differences between (`var.worker_groups`, `var.worker_groups_launch_template`) Workers Groups and (`var.node_groups`) Managed Node Groups

### ISSUE THREAD

**Issue by mmgari** [terraform-aws-modules/terraform-aws-eks#1077] opened 2020-10-29 13:22 UTC
# Whats the difference between Workers and Nodes?

First, my apologies if this is not the place for these kind of questions.

I was wondering if anyone can point me some basic differences between Worker groups and Node groups. If I create a node group, I am able to see it from the AWS console in the "compute" section of the cluster. But if I create a worker-group, I only see it if I query the cluster with `kubectl get nodes`.

Thanks!

**Comment by fcervantes2** [comment] 2020-10-30 23:13
`worker_nodes` are "self-managed" node groups, while `node_groups` are AWS-managed node-groups. It would be nice to have a renaming of these variables to make the distinction a bit more clearer. For more info, I suggest you look at the official docs: https://docs.aws.amazon.com/eks/latest/userguide/eks-compute.html

**Comment by mmgari** [comment] 2020-11-02 16:42
Thank you! Cristal clear.

**Comment by dzirg44** [comment] 2020-11-02 21:08
Also it would be fair to mention that `node_groups` don't allow you to use spot instances.

**Comment by barryib** [comment] 2020-11-02 21:33
Can someone update the FAQ please ?

**Comment by jeff-knurek** [comment] 2020-11-03 10:41
This is a duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/895 
but this module does need some better documentation (FAQ update?) so it doesn't continue to keep getting asked.

**Comment by barryib** [comment] 2020-11-03 11:16
> This is a duplicate of #895
> but this module does need some better documentation (FAQ update?) so it doesn't continue to keep getting asked.

Yep. I'll happy to review and merge the PR.

> Sure, I can write something up when I find free time.

Maybe @pranas https://github.com/terraform-aws-modules/terraform-aws-eks/issues/895#issuecomment-688927130 ?

**Comment by pranas** [comment] 2020-11-03 12:13
Sorry, I lost track of this promise. I'm gonna do it right now and open PR so everyone can pitch in on what exactly should be there.

**Comment by barryib** [comment] 2020-11-03 20:36
Closing this since #1081 is now merged.

**Closed by barryib** 2020-11-03 20:36 UTC
