### ISSUE TITLE
Changed order of subnets forces recreate

### ISSUE THREAD

**Issue by hameno** [terraform-aws-modules/terraform-aws-eks#1006] opened 2020-09-10 15:36 UTC
# I have issues
I'm getting a list of subnet for EKS via a data source like this:
```
data "aws_subnet_ids" "private_subnets" {
  vpc_id = var.vpc_id
  tags = {
    "Tier" = "private"
  }
}
```
Previously I used a direct reference to the output of the aws/vpc module. When I switched to the data source, the order of the subnet ids changed and this caused a plan that would recreate the EKS cluster. 

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

see above

## If this is a bug, how to reproduce? Please include a code sample if relevant.

see above

## What's the expected behavior?

I think the order should not matter

## Environment details

* Affected module version: 12.2.0
* OS: Windows 10 WSL Ubuntu
* Terraform version: v0.13.1

**Comment by dpiddockcmp** [comment] 2020-09-11 07:22
This is a limitation of the aws provider. It is not something we can fix in the module, certainly not without breaking a lot existing clusters. Please raise an issue over on the provider: https://github.com/terraform-providers/terraform-provider-aws

**Comment by hameno** [comment] 2020-09-11 07:25
Ok, can do. Which low-level ressource would that correspond to?

**Comment by dpiddockcmp** [comment] 2020-09-11 07:27
It's the [`aws_eks_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster)

**Comment by hameno** [comment] 2020-09-11 07:55
Ok, thanks, create an issue there

**Comment by dpiddockcmp** [comment] 2020-09-11 08:12
I'm going to close this issue as it is not a bug with the module.

**Closed by dpiddockcmp** 2020-09-11 08:12 UTC

**Comment by bflad** [comment] 2020-09-11 16:29
Hi @dpiddockcmp 👋  Looking at https://github.com/terraform-providers/terraform-provider-aws/issues/15113, there does not seem to be an indication of a Terraform AWS Provider issue. Can you please let us know why you think this is?

**Comment by dpiddockcmp** [comment] 2020-09-11 16:43
The original report here was very vague. Sorry. But the fuller content over on the provider issue shows that there is no recreation of the eks_cluster, only an unimportant extra resource.

This should be closed as user misunderstanding.

**Comment by hameno** [comment] 2020-09-11 16:45
I'm sorry, I should clarify: it forces a recreation of the managed nodes which imo should not happen

**Comment by dpiddockcmp** [comment] 2020-09-12 12:41
Please provide the full change output from terraform. The original issue claimed the whole cluster gets recreated. The issue opened against the AWS provider (sorry, my bad) only mentions a `random_pet` getting recreated.

**Comment by hameno** [comment] 2020-09-12 12:58
Here is the (anonymized) output
```
  # module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["0"] must be replaced
+/- resource "aws_eks_node_group" "workers" {
      ~ ami_type        = "AL2_x86_64" -> (known after apply)
      ~ arn             = "arn:aws:eks:eu-central-1:111111111111:nodegroup/eks-development/eks-development-0-eager-mastodon/e4ba3c69-ff4e-f15f-9849-5d2875503073" -> (known after apply)
        cluster_name    = "eks-development"
      ~ disk_size       = 20 -> (known after apply)
      ~ id              = "eks-development:eks-development-0-eager-mastodon" -> (known after apply)
        instance_types  = [
            "t3.medium",
        ]
      - labels          = {} -> null
      ~ node_group_name = "eks-development-0-eager-mastodon" -> (known after apply) # forces replacement
        node_role_arn   = "arn:aws:iam::111111111111:role/eks-development20200902115627222700000007"
      ~ release_version = "1.17.9-20200904" -> (known after apply)
      ~ resources       = [
          - {
              - autoscaling_groups              = [
                  - {
                      - name = "eks-e4ba3c69-ff4e-f15f-9849-5d2875503073"
                    },
                ]
              - remote_access_security_group_id = ""
            },
        ] -> (known after apply)
      ~ status          = "ACTIVE" -> (known after apply)
        subnet_ids      = [
            "subnet-1111111111111111",
            "subnet-2222222222222222",
            "subnet-3333333333333333",
        ]
        tags            = {
            "env"   = "development"
            "group" = "development"
        }
      ~ version         = "1.17" -> (known after apply)

      ~ scaling_config {
          ~ desired_size = 1 -> 3
            max_size     = 3
            min_size     = 1
        }
    }

  # module.eks.module.eks.module.node_groups.random_pet.node_groups["0"] must be replaced
+/- resource "random_pet" "node_groups" {
      ~ id        = "eager-mastodon" -> (known after apply)
      ~ keepers   = { # forces replacement
            "iam_role_arn"              = "arn:aws:iam::111111111111:role/eks-development20200902115627222700000007"
            "instance_type"             = "t3.medium"
            "key_name"                  = ""
            "node_group_name"           = "eks-development-0"
            "source_security_group_ids" = ""
          ~ "subnet_ids"                = "subnet-1111111111111111|subnet-3333333333333333|subnet-2222222222222222" -> "subnet-1111111111111111|subnet-2222222222222222|subnet-3333333333333333"
        }
        length    = 2
        separator = "-"
    }
```

**Comment by dpiddockcmp** [comment] 2020-09-14 08:07
Ok. That's expected behaviour.

To avoid total downtime of services we need to use "create before destroy" on the EKS Managed Node Group resource. But MNG must have unique names. The Terraform `eks_node_group` resource itself does not have a `name_prefix` attribute like a lot of the older resources. Instead we use a `random_pet` to generate the unique name element. When the inputs to the `random_pet` change it causes a recreate event. You have changed the inputs to the `random_pet` by reordering the subnet IDs.

Applying this change is not going to recreate your whole cluster. It will cause new EC2 instances to be created, the EKS system will cleanly migrate pods to the new nodes and then delete the old nodes and node group.

Maybe we could try to handle the list of subnets as a terraform set before handing to `random_pet` to avoid this particular issue in future. This will create a predictable ordering of the subnet ids. Unfortunately it's also a breaking change that will cause recreation of node groups for some existing users.
