### ISSUE TITLE
New AWS-auth module doesn't respect the nodeGroup perrms

### ISSUE THREAD

**Issue by taer** [terraform-aws-modules/terraform-aws-eks#2952] opened 2024-03-05 00:48 UTC
In version 19, the config map contained something like this 
```
  - resource "kubernetes_config_map_v1_data" "aws_auth" {
      - data          = {
          - "mapAccounts" = jsonencode([])
          - "mapRoles"    = <<-EOT
                - "groups":
                  - "system:bootstrappers"
                  - "system:nodes"
                  "rolearn": "arn:aws:iam::xxx:role/initial-arm-eks-node-group-20240213202243321100000003"
                  "username": "system:node:{{EC2PrivateDNSName}}"
                - "groups":
                  - "system:masters"
                  "rolearn": "arn:aws:iam::xxx:role/GitHubActionsOIDC"
                  "username": "gh-role"
                - "groups":
                  - "system:masters"
                  "rolearn": "arn:aws:iam::xxx:role/hub-control-plane-hub-role"
                  "username": "allow-remote-control"
```

in 20 with the new aws-auth module change, we get this 
```
  + resource "kubernetes_config_map_v1_data" "aws_auth" {
      + data          = {
          + "mapAccounts" = jsonencode([])
          + "mapRoles"    = <<-EOT
                - "groups":
                  - "system:masters"
                  "rolearn": "arn:aws:iam::xxx:role/GitHubActionsOIDC"
                  "username": "gh-role"
                - "groups":
                  - "system:masters"
                  "rolearn": "arn:aws:iam::xxx:role/hub-control-plane-hub-role"
                  "username": "allow-remote-control"
            EOT
```

In 19, the eks took the `aws_auth_roles` parameter, and ammeded it to a whole set of other roles. in 20, the input is the whole set.

The upgrade docs for 20 doesn't mention a good workaround.

The `code` lost in the upgrade took this 
```
  node_iam_role_arns_non_windows = distinct(
    compact(
      concat(
        [for group in module.eks_managed_node_group : group.iam_role_arn if group.platform != "windows"],
        [for group in module.self_managed_node_group : group.iam_role_arn if group.platform != "windows"],
        var.aws_auth_node_iam_role_arns_non_windows,
      )
    )
  )
```

and merged it with the data supplied in the 0.19 module parameter of `aws_auth_roles`   in 0.20, `aws_auth_roles` is the sole truth. So if one applied the upgrade as documented, the node-groups would be removed from the aws-auth CM.

**Comment by bryantbiggs** [comment] 2024-03-05 00:59
> So if one applied the upgrade as documented, the node-groups would be removed from the aws-auth CM.

Correct, that's the intent

**Comment by taer** [comment] 2024-03-05 02:47
OK. As long as it's known. A mention of that in the upgrade notes might help. The terraform plan had a bit of noise in it, so people might miss the loss of node-group perms. 

The `Upgrade Migrations` section implies a lossless transition. Put a little PR in place Not a word-smith by any means but added a brief warning here. https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2953

**Comment by taer** [comment] 2024-03-05 02:51
I might have missed any other warning. But I feel that this is a pretty significant delta that would only bite people well after the miss.   

If people miss this, I think their cluster will continue to work perfectly. But any managed node groups would slowly and confusingly shrink as their ASG's cycle. The new replacement nodes wouldn't register, and it undoubtedly happen week sor months after the mistake, making it really hard to diagnose the issue.

**Comment by bryantbiggs** [comment] 2024-03-05 11:16
<img width="800" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/10913471/b13ae0fa-f5d4-4610-9b85-f6170e0e9f86">

and 

<img width="802" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/10913471/e8880c24-7c55-458a-ab83-abd28f176edc">

and

<img width="810" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/10913471/0dee72a1-f724-482c-a5ad-d53567218abe">


I think its pretty clear - unfortunately, this looks like a case where we might not have read the docs first before performing the upgrade 😅 . closing these out for now since I believe the upgrade docs are quite clear about the behaviors and actions

**Closed by bryantbiggs** 2024-03-05 11:16 UTC

**Comment by tim-hutchinson** [comment] 2024-03-06 16:35
@bryantbiggs Speaking as someone going through this now, I'm not sure it's as clear as claimed.

The module v20 upgrade guide also contains the following note:
> Note - EKS automatically adds access entries for the roles used by EKS managed nodegroups and Fargate profiles; users do not need to do anything additional for these roles

However, within the [AWS migration guide](https://docs.aws.amazon.com/eks/latest/userguide/migrating-access-entries.html), there's this seemingly contradictory note, that I believe is what the OP is referencing here
> Important
> Don't remove existing aws-auth ConfigMap entries that were created by Amazon EKS when you added a [managed node group](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html) or a [Fargate profile](https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html) to your cluster. If you remove entries that Amazon EKS created in the ConfigMap, your cluster won't function properly. You can however, remove any entries for [self-managed](https://docs.aws.amazon.com/eks/latest/userguide/worker.html) node groups after you've created access entries for them.

The plan on upgrading to v20 shows the removal of the ConfigMap entries that the AWS documentation seems to explicitly say not to remove. I understand that on _new_ managed nodegroups, the `aws-auth` configmap entry would be correctly created by EKS. However, during an upgrade these nodegroups already exist and so does the configmap entry, which would not be recreated by EKS when removed by the Terraform plan

**Comment by bryantbiggs** [comment] 2024-03-06 17:28
> The plan on upgrading to v20 shows the removal of the ConfigMap entries that the AWS documentation seems to explicitly say not to remove.

I can try to work on getting the wording updated a little better in the docs; its perfectly safe and valid to remove the `aws-auth` ConfigMap entries for managed nodegroups and Fargate profiles after migrating to cluster access entries

> Maybe this is a confusion over what "anything additional" refers to. From my reading, I would consider using the clowdhaus module snapshot and manually removing the ConfigMap from state as "additional" (as in, in-addition to upgrading the module), but you might be referring to steps that are in addition to those two steps?

I don't quite follow this. The point of the [one-time upgrade module](https://github.com/clowdhaus/terraform-aws-eks-migrate-v19-to-v20) is to provide a better (smoother) path to upgrade existing clusters to use cluster access entries. If we did not provide this intermediate module/step, after changing the module version to v20.0 we would have a race condition that could pose problematic for users when upgrading. In that scenario, there is no guarantee that the cluster acess entry is enabled and the respective cluster access entries for managed nodegroups and Fargate profiles are created BEFORE Terraform deletes the `aws-auth` ConfigMap. So this intermediate module/step is a mix of v20.0 but with the `aws-auth` functionality still provided, which allows users to upgrade to cluster access entries without any distrubance to the `aws-auth` configmap. After cluster access entry is enabled, then you can move on to v20.x and this is where the ConfigMap will be destroyed by Terraform. If you need to retain/update the `aws-auth` ConfigMap, please see the upgrade docs for the different options and their respective paths for completing the upgrade

**Comment by tim-hutchinson** [comment] 2024-03-06 18:48
> its perfectly safe and valid to remove the aws-auth ConfigMap entries for managed nodegroups and Fargate profiles after migrating to cluster access entries

What you're claiming here about the additional entries seems like its in direct conflict with the contents of AWS's own documentation. Not saying that you're wrong, just that the AWS docs say in a big red callout "don't remove these".

>I don't quite follow this. 

Me either, it was me attempting to try to understand if I was reading the guide as intended. It seems that I was reading it as intended, and its the claim about whether those entries are needed at all that's relevant here.
