### ISSUE TITLE
Question regarding autoscaling group and launch template.

### ISSUE THREAD

**Issue by Monikaa7** [terraform-aws-modules/terraform-aws-eks#1829] opened 2022-02-02 12:53 UTC
Is it possible with this module to have the below steup? 
EKS cluster --> node group --> autoscaling group --> custom launch template

In what I discovered if i remove the dynamic block in the node_group resource:

  dynamic "launch_template" {
   for_each = local.use_custom_launch_template ? [1] : []
   content {
     name    = local.launch_template_name
     version = local.launch_template_version
   }
  }

What I achieve is the above setup, however the launch template is using the default values, not the one that I set.
And specifically I need to use gp3 in my launch template, which needs to be attached only the auto-scaling, not to the node group itself.
The thing is that I want to match a current infrastructure and migrate to use the new module, but I am not able to achieve the same setup because of the launch template values.

Can you let me know if that's possible to achieve and give me some guidance on how to do that?
Thank you in advance.

**Comment by bryantbiggs** [comment] 2022-02-02 12:57
Yes, you can do this. If you have a launch template already created, you can pass it into the module like this https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d0de694b66dd1f69c2ea3d35bef423a1d0d6d5a2/examples/eks_managed_node_group/main.tf#L158

You can also set the configurations within the module as well which gets passed to a custom launch template that the module creates for you - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L250-L263

**Comment by Monikaa7** [comment] 2022-02-02 13:04
Thank you for the answer. I already tried what you're saying, but for some reason it's not working for me.
This is how my node group configuration looks like:

eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    disk_size      = 50
    instance_types = "t3.medium"
  }

  eks_managed_node_groups = {

    test_nodegroup = {
      launch_template_name    = "test_nodegroup-2022020210020710010000000f"
      launch_template_version = "1"
      use_name_prefix = true

      subnet_ids            = module.vpc.private_subnets
      create_security_group = false

      min_size     = 1
      max_size     = 5
      desired_size = 1

      disk_size      = 50
      volume_type    = "gp3"
      ebs_optimized  = true
      instance_types = "t3.medium"
      capacity_type  = "ON_DEMAND"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 75
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            encrypted             = true
            delete_on_termination = true
          }
        }
      }
    }
I have the needed launch template created, however the one that my autoscaling group is using remains the one with the default values.

**Comment by bryantbiggs** [comment] 2022-02-02 13:18
what version of the module are you using (we put the issue templates in here for a reason)?

**Comment by Monikaa7** [comment] 2022-02-02 13:41
I think it's 18.0.0, but I am not sure if I am looking at the correct page for the version.

**Comment by bryantbiggs** [comment] 2022-02-02 14:02
from your working directory, if you run `terraform version` it will show you the versions of your providers used as well as Terraform

**Comment by Monikaa7** [comment] 2022-02-02 14:21
Okay, great thanks for explanation, I was looking at the version of the module.
You can see below all the versions:

Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

**Comment by bryantbiggs** [comment] 2022-02-02 14:46
apologies, I was on mobile and told you wrong. Yes, we are looking for the module version - it should be defined in the module definition you are using, like:

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.2"
  ...
}
``

**Comment by Monikaa7** [comment] 2022-02-02 14:50
no worries, but unfortunately I don't have a version set in the module definition

**Comment by bryantbiggs** [comment] 2022-02-02 14:59
and have you set `create_launch_template  = false` like I pointed to above?

**Comment by Monikaa7** [comment] 2022-02-02 15:15
If i put it to false like pointed it tries to delete my custom launch template that I want to use for the autoscaling.

**Comment by bryantbiggs** [comment] 2022-02-02 15:18
I don't follow what you are doing - have you looked at the modules? if you want to use the launch template created by the module then you don't need to set all this:
```hcl
  launch_template_name    = "test_nodegroup-2022020210020710010000000f"
  launch_template_version = "1"
  use_name_prefix = true
```
The following can only be used when relying on the EKS managed node group default launch template. Which here you are not doing so these aren't doing anything:
```hcl
  disk_size      = 50
  volume_type    = "gp3"
```

Please check the examples for reference, they are well documented for various use cases

**Comment by Monikaa7** [comment] 2022-02-02 15:28
I looked at the examples for several days and tried different configurations. An example as my use case does not exist, as far as I see. But maybe you didn't understood exactly my question, I will try to explain with more details.

The configuration currently of the module is to have the launch template set in the node group.
I don't want to do that, I want the launch template to be only attached to my autoscaling group. I figured how to remove the launch template from the node group. However it creates 2 templates - one with the default values and second one with my customer values. My question is how to tell to the autoscaling group to use my custom template. I need the launch template to be only defined in the autoscaling, but I am not sure if it's possible to do, that was my whole question.

**Comment by philicious** [comment] 2022-02-02 16:10
@Monikaa7 not sure if I get you right but to give some general feedback that my help solve this:

> The configuration currently of the module is to have the launch template set in the node group.
I don't want to do that, I want the launch template to be only attached to my autoscaling group

If you are using a MNG, then it will, by design, always haven an LT assigned, which it uses for the managed ASG to create EC2s.
If you dont specify your own custom LT, then EKS will create a default one for you.

>However it creates 2 templates - one with the default values and second one with my customer values

not sure if this it what you observe, but EKS will make a copy of your custom LT and use the copy in the ASG

**Comment by nmofonseca** [comment] 2022-02-04 10:01
Hi everyone, 

First of all, I want to thank the creators and maintainers of the module, is really great work and an amazing module! 

However my use case is not the same, I am trying to create a fresh new EKS cluster in a new AWS account, I used to use Version 17 of the module but since it's a new account I am giving a go to v18 latest, so my use case is a fresh new EKS cluster creation, not upgrade and nothing was there before.

I believe the disk_size values are not applied at all and I am using the complete example as a guide in how to convert the v17 code to v18. I am using EKS managed node group and the EC2 instances are always created with 20Gb volumes regardless of what I do, this is my node group config:

```
  #EKS managed node group defaults and config
  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    key_name       = "mykey"
  }

  eks_managed_node_groups = {
    eks-preprod-nodes = {
      min_size     = 2
      max_size     = 10
      desired_size = 2
      disk_size      = 30
      instance_types = var.kubernetes_worker_instance_types
      capacity_type  = "ON_DEMAND"
      labels = local.tags

      update_config = {
        max_unavailable_percentage = 50 # or set `max_unavailable`
      }

      tags = local.tags
    }
  }
  
  tags = local.tags
}

```

I am sure I am doing something wrong but I don't seem to be able to understand what? Does anyone have any ideas?

Cheers.

**Comment by bryantbiggs** [comment] 2022-02-07 20:53
closing for now - please refer to examples provided for various usage patterns

**Closed by bryantbiggs** 2022-02-07 20:53 UTC
Labels: question
