### ISSUE TITLE
upgrade from eks 18.x.x to 19.x.x, new nodes are not getting attached to the cluster

### ISSUE THREAD

**Issue by vasenthilkumar** [terraform-aws-modules/terraform-aws-eks#2735] opened 2023-09-06 21:06 UTC
## Description

After upgrading to version 19.16.0 from 18.31.2, the upgrade was smooth but when I tried to increase the desired capacity on the auto scaling groups, new nodes are created but not getting attached to the cluster.

## Versions

- Module version [Required]: 19.16.0

- Terraform version: 1.1.7
  1.5.6
- Provider version(s): 19.16.0

## Expected behavior

New nodes added to the cluster

## Actual behavior

New ec2 nodes created on the aws console but not getting attached to the cluster

**Comment by bryantbiggs** [comment] 2023-09-07 12:16
without any reproduction its unclear how we can help. I would suggest looking at logs - starting with the cloud-init output logs, kubelet logs, etc.

**Comment by vasenthilkumar** [comment] 2023-09-07 19:35
The issue is same as #2608 where the documentation is wrong, we would have to do a terraform move with these commands for the cluster iam role to have the exisitng policies attached. 
`terraform state mv module.eks.aws_iam_role_policy_attachment.this[\"arn:aws:iam::aws:policy/AmazonEKSVPCResourceController\"] module.eks.aws_iam_role_policy_attachment.this[\"AmazonEKSVPCResourceController\"]`
`terraform state mv module.eks.aws_iam_role_policy_attachment.this[\"arn:aws:iam::aws:policy/AmazonEKSClusterPolicy\"] module.eks.aws_iam_role_policy_attachment.this[\"AmazonEKSClusterPolicy\"]`

The documentation for cluster iam role is wrong which asks us to move to a policy key map [https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#cluster-iam-role](url)

**Comment by bryantbiggs** [comment] 2023-09-07 19:50
I am going to close this for now since its not clear what the issue is - please provide the necessary details for us to properly troubleshoot and triage

**Closed by bryantbiggs** 2023-09-07 19:50 UTC

**Comment by kh34** [comment] 2023-09-15 16:51
I also experienced this issue. Please re-open.

```
  # module.eks_cluster.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"] will be destroyed
  # (because key ["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"] is not in for_each map)
  - resource "aws_iam_role_policy_attachment" "this" {
      - id         = "<omitted>-20230215165425945300000010-20230215165426680600000020" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy" -> null
      - role       = "<omitted>-20230215165425945300000010" -> null
    }
  # module.eks_cluster.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"] will be destroyed
  # (because key ["arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"] is not in for_each map)
  - resource "aws_iam_role_policy_attachment" "this" {
      - id         = "<omitted>-20230215165425945300000010-2023021516542666610000001f" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController" -> null
      - role       = "<omitted>-20230215165425945300000010" -> null
    }
```
