### ISSUE TITLE
Userdata Template whitespace stripping causes userdata issues

### ISSUE THREAD

**Issue by rteeling** [terraform-aws-modules/terraform-aws-eks#2581] opened 2023-04-19 22:46 UTC
## Description

The Linux userdata template has an issue with formatting if you enable bootstrap userdata and provide pre-bootstap user data 

If your request is for a new feature, please use the `Feature request` template.

- [x]  ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 19.12.0

- Terraform version:
1.1.2
- Provider version(s):
registry.terraform.io/hashicorp/aws: 4.61.0

## Reproduction Code [Required]

```
### RELEVANT SECTION ###
  eks_managed_node_groups = {
    system = {
      name = "system"
      use_name_prefix = false

      ami_id         = REDACTED
      ami_type       = "CUSTOM"
      instance_types = ["m6a.2xlarge"]

      create_iam_role            = false
      iam_role_arn               = REDACTED
      iam_role_attach_cni_policy = false


      force_update_version = true


      ebs_optimized = true
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_type = "gp3"
            volume_size = "300"
            throughput  = "300"
            iops        = "3000"
          }

        } 

      }

      enable_bootstrap_user_data = true
      pre_bootstrap_user_data = templatefile(
        "${path.module}/templates/userdata-pre.tpl",
        {
          docker_auth = var.docker_auth
      })
      bootstrap_extra_args = "--cpu-manager-policy static   --node-labels zone=system --max-pods 45"

      min_size     = 2
      max_size     = 5
      desired_size = 2
    }
###
```
Template file:
```
cat <<EOF > /var/lib/kubelet/config.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "${docker_auth}"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.6-ce (linux)"
        }
}
EOF
```
! Note there is no newline at the end of the template file

 
Create a managed nodegroup with managed launch template, set `enable_bootstrap_user_data = true`,
then provide templated `pre_bootstrap_user_data` WITHOUT a newline at the end

## Expected behavior

Linux userdata has correct newlines, like this:
```
#!/bin/bash
set -e
cat <<EOF > /var/lib/kubelet/config.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "[REDACTED]"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.6-ce (linux)"
        }
}
EOF
B64_CLUSTER_CA=[REDACTED]
API_SERVER_URL=[REDACTED]
/etc/eks/bootstrap.sh dev-poc-rob --cpu-manager-policy static   --node-labels zone=system --max-pods 45 --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL
```
## Actual behavior

```
#!/bin/bash
set -e
cat <<EOF > /var/lib/kubelet/config.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "[REDACTED]"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.6-ce (linux)"
        }
}
EOFB64_CLUSTER_CA=[REDACTED]
API_SERVER_URL=[REDACTED]
/etc/eks/bootstrap.sh dev-poc-rob --cpu-manager-policy static   --node-labels zone=system --max-pods 45 --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL

```

Notice how the final EOF of the heredoc should have  a newline after, but is instead directly contcatenated with the `B64_CLUSTER_CA`

**Comment by bryantbiggs** [comment] 2023-04-22 00:29
I don't believe this is an issue with the module - I believe the issue lies with your use of your template and or templatefile. Closing this for now since everything appears to be working as intended, please feel free to checkout our user data examples for further details/tests

**Closed by bryantbiggs** 2023-04-22 00:29 UTC
