### ISSUE TITLE
example code in README and in examples dir doesn't work

### ISSUE THREAD

**Issue by st33v** [terraform-aws-modules/terraform-aws-eks#734] opened 2020-02-11 00:54 UTC
# I have issues
I can't get the example in the readme to work without removing the kubernetes provider

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
if I try to use the module as described in the README... 

```
data "aws_eks_cluster" "cluster" {
  name = module.my-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.my-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.14"
  subnets         = ["subnet-abcde012", "subnet-bcde012a", "subnet-fghi345a"]
  vpc_id          = "vpc-1234556abcdef"

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]
}
```

it fails unless I remove the provider block and I get the error:

```
Error: Failed to initialize config: invalid configuration: no configuration has been provided

  on providers.tf line 6, in provider "kubernetes":
   6: provider "kubernetes" {
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
follow the example in the README.md 

## What's the expected behavior?
I'd expect the example to work but I understand why it would fail if the k8s cluster does not yet exist.

## Are you able to fix this problem and submit a PR? Link here if you have already.
no, sorry. I don't understand how it should have worked in the first place... how could you use a provider that doesn't yet exist?

## Environment details

Terraform v0.12.20
+ provider.aws v2.48.0
+ provider.kubernetes v1.11.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

**Comment by st33v** [comment] 2020-02-11 01:07
I've also tried the example where the provider and the EKS cluster are conditional and that also does not work.

**Comment by mcavoyk** [comment] 2020-02-11 02:06
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/733, see my comment https://github.com/terraform-aws-modules/terraform-aws-eks/issues/733#issuecomment-584448774

**Comment by barryib** [comment] 2020-04-01 04:36
closing as it duplicates #733.

**Closed by barryib** 2020-04-01 04:36 UTC
