### ISSUE TITLE
Questoin) If you configure NodeGroup using Launch Template, Instance Profile option is not available.

### ISSUE THREAD

**Issue by oliverpark999** [terraform-aws-modules/terraform-aws-eks#2117] opened 2022-06-22 12:02 UTC
If you configure Nodegroup using Launch Template,
Why is Launch Template automatically created?
I configured AWS Load Balancer Controller in Node, but
ALB was not created, so I searched for a few days.
It was because [Launch Template > Instance Profile] was not specified.
However, when trying to configure the Instance Profile, when creating a NodeGroup
An error occurs.
I also confirmed the contents in the official documentation.
How the hell am I supposed to configure it...?

![profile](https://user-images.githubusercontent.com/47516457/175024409-bb3847c2-b109-4dc2-a8d8-906f6e9ad495.png)

**Comment by oliverpark999** [comment] 2022-06-22 12:45
When I checked the log of the aws load balancer controller, I found the following.

`{"level":"error","ts":1655901591.8439481,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"nginx-ingress", "namespace":"dvo-core","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.ap-northeast-2.amazonaws .com/\": dial tcp: i/o timeout"}`

And, under normal circumstances, we found that the aws load balancer controller Security Group was automatically created and ingressed in the Security Group of the Node Instance.

**Comment by bryantbiggs** [comment] 2022-06-22 13:01
EKS managed node groups have two routes:
1. Utilize the default launch template created by the EKS managed node group service
2. Utilize a custom launch template which is *MERGED with the launch template created by EKS managed node group service (hence why you will typically see 2 launch templates in the console for one node group, but only one is used on the ASG of the node group)

That said - I believe your issue is with the IRSA role for your ALB controller due to `"error":"WebIdentityErr: failed to retrieve credentials`. Have you seen https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks

An example of its usage https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-role-for-service-accounts-eks/main.tf#L184-L198

**Comment by oliverpark999** [comment] 2022-06-22 13:15
I've configured everything.
I added AdministratorAccess Policy just in case, but without success.

![q1](https://user-images.githubusercontent.com/47516457/175037521-b752005b-3f87-45d5-8536-db65b5c39136.png)
![q2](https://user-images.githubusercontent.com/47516457/175037530-7a6b3c54-03f0-4553-bd1c-50cff9ccc07b.png)


```
kubectl get serviceaccount 
NAME                                 SECRETS   AGE
attachdetach-controller              1         169m
aws-cloud-provider                   1         169m
aws-load-balancer-controller         1         8m22s
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123213:role/dvo-poc-iac-lb-controller-role
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::1242214:role/dvo-poc-iac-lb-controller-role"},"name":"aws-load-balancer-controller","namespace":"kube-system"}}
  creationTimestamp: "2022-06-22T13:02:17Z"
  name: aws-load-balancer-controller
  namespace: kube-system
  resourceVersion: "28056"
  uid: 23123-dec3-437b-bd01-c02b990bdd53
secrets:
- name: aws-load-balancer-controller-token-fgsnh
```

**Comment by bryantbiggs** [comment] 2022-06-22 13:20
you haven't posted your configuration/reproduction so its hard to say

**Comment by bryantbiggs** [comment] 2022-07-16 14:22
closing out with information provided above

**Closed by bryantbiggs** 2022-07-16 14:22 UTC
Labels: question
