### ISSUE TITLE
Terraform should exit if kubectl doesn't exist for EKS creation

### ISSUE THREAD

**Issue by finnball** [terraform-aws-modules/terraform-aws-eks#378] opened 2019-05-09 15:45 UTC
# I have issues

## I'm submitting a...

* [ ] bug report

### Terraform Version
Terraform v0.11.13

### Script

https://gist.github.com/finnball/bd435ddc8d7aff2c1334e77176e1e0bd

### Expected Behavior

I needs to raise a serious warning and exit.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf#L18

### Actual Behavior
It continues, telling you everything has been applied. Pods are then stuck in `Pending`

### Steps to Reproduce

Terraform apply on a machine which doesn't have kubectl installed. You'll eventually get this single line:

`[0m[0mmodule.eks.null_resource.update_config_map_aws_auth (local-exec): /bin/sh: 52: kubectl: not found`

Terraform will continue and eventually say it has applied it. Pods will then be stuck in `Pending`. Installing kubectl, destroying and finally applying terraform fixes the problem.

**Comment by max-rocket-internet** [comment] 2019-05-13 08:27
Agreed. But this issue is a duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/341

**Closed by max-rocket-internet** 2019-05-13 08:27 UTC
