### ISSUE TITLE
"Invalid count argument" when using "pre_bootstrap_user_data"

### ISSUE THREAD

**Issue by inez** [terraform-aws-modules/terraform-aws-eks#2251] opened 2022-09-30 05:37 UTC
## Description

I'm getting:

```
╷
│ Error: Invalid count argument
│ 
│   on .terraform/modules/eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
│   67:   count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
```

when I'm simply using eks managed node group with a standard ami, but with `pre_bootstrap_user_data` provided.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
- Terraform version: 1.3.0
- Provider version(s): 18.30.0

**Comment by bryantbiggs** [comment] 2022-09-30 11:03
And what is your configuration

**Comment by inez** [comment] 2022-09-30 16:37
> And what is your configuration

Oops, forgot to attach, but here it is:

```
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

data "aws_iam_role" "terraform" {
  name = "CFTerraformRole"
}

data "aws_iam_role" "admin" {
  name = "admin"
}

data "aws_subnet_ids" "example" {
  vpc_id = ...
}

module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "18.30.0"

  cluster_name = "my-cluster-2"
  cluster_version = "1.23"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access = false

  vpc_id = ...

  subnet_ids = data.aws_subnet_ids.example.ids

  node_security_group_additional_rules = {
    cluster_to_node_8443 = {
      description      = "Cluster to ingress-nginx webhook"
      protocol         = "-1"
      from_port        = 8443
      to_port          = 8443
      type             = "ingress"
      source_cluster_security_group = true
    }    
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
    ingress_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }

  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
    ingress = {
      description                = "To node 1025-65535"
      type                       = "ingress"
      from_port                  = 0
      to_port                    = 0
      protocol                   = -1
      cidr_blocks                = ["0.0.0.0/0"]
      source_node_security_group = false
    }
    egress = {
      type                       = "egress"
      protocol   = -1
      cidr_blocks = ["0.0.0.0/0"]
      from_port  = 0
      to_port    = 0
    }
  }

  cluster_addons = {
    coredns = { resolve_conflicts = "OVERWRITE" }
    kube-proxy = {}
    vpc-cni = { resolve_conflicts = "OVERWRITE" }
    aws-ebs-csi-driver = { resolve_conflicts = "OVERWRITE" }
  }

  eks_managed_node_group_defaults = {
    iam_role_attach_cni_policy = true
    ami_type       = "AL2_x86_64"
  }

  eks_managed_node_groups = {
    one = {
      pre_bootstrap_user_data = <<-EOT
...
      EOT

      key_name = aws_key_pair.key_pair.key_name
      min_size     = 0
      max_size     = 3
      desired_size = 1
      instance_types = ["c5.2xlarge"]
      capacity_type  = "SPOT"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 500
            volume_type           = "gp3"
            delete_on_termination = true
          }
        }
      }

    }
  }

  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = data.aws_iam_role.admin.arn
      username = "admin"
      groups   = ["system:masters"]
    },
    {
      rolearn  = data.aws_iam_role.terraform.arn
      username = "terraform"
      groups   = ["system:masters"]
    },
    {
      rolearn = module.eks.eks_managed_node_groups.one.iam_role_arn,
      username = "system:node:{{EC2PrivateDNSName}}"
      groups   = ["system:bootstrappers", "system:nodes"]
    }
    ]
}
```

**Comment by bryantbiggs** [comment] 2022-10-03 16:12
I'm not able to reproduce the error. Are you providing anything in the `pre_bootstrap_user_data` field?

**Comment by bryantbiggs** [comment] 2022-10-13 14:47
closing since I am unable to re-produce the error

**Closed by bryantbiggs** 2022-10-13 14:47 UTC
Labels: question

**Comment by inez** [comment] 2022-10-20 04:23
Yes, I do have content in `pre_bootstrap_user_data`, this is just the snippet:

```
      pre_bootstrap_user_data = <<-EOT
Content-Type: multipart/mixed; boundary="==BOUNDARY=="
MIME-Version:  1.0
--==BOUNDARY==
Content-Type: text/cloud-boothook; charset="us-ascii"

#Set the proxy hostname and port
PROXY="...
```

I noticed that the easiest way to reproduce for me is to create cluster, then destroy it, and try creating again <- that's when it fails.
