### ISSUE TITLE
[Deprecation Warning] "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation

### ISSUE THREAD

**Issue by goetzc** [terraform-aws-modules/terraform-aws-eks#2823] opened 2023-11-20 15:07 UTC
## Description

In a new AWS account and new Terraform setup, after the plan (or apply) is run and shown, the following warning is displayed:

```
│ Warning: Argument is deprecated
│
│   with module.eks.module.eks.aws_eks_addon.this["coredns"],
│   on .terraform/modules/eks.eks/main.tf line 399, in resource "aws_eks_addon" "this":
│  399:   resolve_conflicts        = try(each.value.resolve_conflicts, "OVERWRITE")
│
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or "resolve_conflicts_on_update" instead
│
│ (and 3 more similar warnings elsewhere)
╵
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

```
source  = "terraform-aws-modules/eks/aws"
version = "~> 19.20.0"
```

- Terraform version: Terraform v1.5.7
- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.26.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

```tf 
module "eks" {

  # …

  cluster_addons = {
    coredns            = local.default_addon_configuration
    aws-ebs-csi-driver = local.default_addon_configuration
    kube-proxy         = local.default_addon_configuration
    vpc-cni            = local.default_addon_configuration
  }
}

```tf
locals {
  default_addon_configuration = {
    resolve_conflicts_on_create = "OVERWRITE"
    resolve_conflicts_on_update = "PRESERVE"
  }
}
```

`terraform plan` or `terraform apply`.

- Are you using workspaces? Yes
- Have you cleared the local cache (see Notice section above)? Yes

## Expected behavior

There should not be any deprecation warning from module.

## Actual behavior

There is a deprecation warning.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/2220440/69ed758f-0405-4743-bf16-d400f175d3be)

**Comment by bryantbiggs** [comment] 2023-11-21 02:04
its a warning, not an error - closing as a duplicate of #2635

**Closed by bryantbiggs** 2023-11-21 02:04 UTC
