### ISSUE TITLE
Karpenter sub-module's IAM role doesn't provide the necessary rights for running and removing EC2 instances

### ISSUE THREAD

**Issue by disparo13** [terraform-aws-modules/terraform-aws-eks#2605] opened 2023-05-10 10:08 UTC
## Description

I know - it MUST work, but it doesn't.

I'm trying to run Karpenter inside the EKS cluster in the account, let's say - 111111111111. IRSA creating a role with such permissions, and I'm not using `terraform-aws-eks` main module to create "my-eks-cluster" - I'm creating it on my own. 

```
{
    "Statement": [
        {
            "Action": [
                "pricing:GetProducts",
                "ec2:DescribeSubnets",
                "ec2:DescribeSpotPriceHistory",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeImages",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateTags",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:111111111111:launch-template/*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:111111111111:volume/*",
                "arn:aws:ec2:*:111111111111:subnet/*",
                "arn:aws:ec2:*:111111111111:spot-instances-request/*",
                "arn:aws:ec2:*:111111111111:security-group/*",
                "arn:aws:ec2:*:111111111111:network-interface/*",
                "arn:aws:ec2:*:111111111111:instance/*"
            ],
            "Sid": ""
        },
    
            {
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
```
So Karpenter can run and get spot prices. Still, when I'm trying to scale my deployment, it only can create a launch template but fails to spin up the instance from it with `UnauthorizedOperation: You are not authorized to perform this operation` errors. The workaround is to moving of `ec2:RunInstances` to the 
```
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
```
policy section. But when I'm scaling down my deployment, it's again - cannot delete created earlier EC2 instance and template before I moving both `ec2:TerminateInstances` and `ec2:DeleteLaunchTemplate` actions to the same policy section.

## Versions

- Module version [Required]: 19.13.1

- Terraform version:
1.4.2
- Provider version(s):
aws:4.64
- Karpenter version:
0.27.3

## Reproduction Code [Required]

```
module "karpenter" {
  source = "terraform-aws-modules/eks/aws//modules/karpenter"

  cluster_name = module.main_eks[0].eks_cluster["name"]

  create_iam_role = false
  iam_role_arn    = module.main_eks[0].worker_role_arn

  create_instance_profile = false

  irsa_name                 = "mine-karpenter-controller"
  irsa_max_session_duration = 43200

  iam_role_use_name_prefix = false
  irsa_use_name_prefix     = false

  irsa_oidc_provider_arn          = module.main_eks[0].aws_iam_openid_connect_provider["arn"]
  irsa_namespace_service_accounts = ["karpenter:karpenter"]
  
  tags = {
    format("kubernetes.io/cluster/%s", module.main_eks[0].eks_cluster["name"]) = "owned"
    Terraform                                                                  = "true"
  }
}

```

## Expected behavior

Karpenter can run and operate as expected.

## Actual behavior

Karpenter could not operate as expected before some of its policy actions were not allowed with the asterisk ("*") wildcard

**Comment by disparo13** [comment] 2023-05-11 10:53
UPDATE: I checked the CloudFormation template by the link from the "Getting started" 
[https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml](https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml) 

They've used global access to "ec2:DeleteLaunchTemplate", "ec2:RunInstances", "ec2:TerminateInstances" in their role's policy as well.

```
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              # Write Operations
              - ec2:CreateFleet
              - ec2:CreateLaunchTemplate
              - ec2:CreateTags
              - ec2:DeleteLaunchTemplate
              - ec2:RunInstances
              - ec2:TerminateInstances
              # Read Operations
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeInstanceTypes
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeSubnets
              - pricing:GetProducts
              - ssm:GetParameter
```

**Comment by bryantbiggs** [comment] 2023-05-12 12:16
please provide a full reproduction - we have an example that demonstrates a working Karpenter implementation here https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/karpenter

**Comment by disparo13** [comment] 2023-05-12 12:31
@bryantbiggs What's still isn't clear after my explanation? What kind of "full reproduction" do you need?

**Comment by bryantbiggs** [comment] 2023-05-12 12:33
The bit of code you provided is only 1/3-1/4 of the equation and it doesn't replicate the issue you are describing

**Comment by bryantbiggs** [comment] 2023-05-12 17:27
great - do you have a reproduction?

**Comment by kjamieson-xilis** [comment] 2023-05-12 18:04
I'll attempt to deploy all of https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/karpenter/main.tf into my account, and then see if I can compare the results to what I'm experiencing just using the stanza from line 157

**Comment by bryantbiggs** [comment] 2023-05-12 19:00
I mean, you are picking just small pieces and not treating them as part of the orchestrated whole. To run Karpenter you need several things working in concert:
1. A VPC [with or without tags](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L311-L315) depending on how you are telling Karpenter [where it will be deploying resources](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L238-L239)
2. An EKS cluster which the Karpenter instance profile [IAM role can authenticate with](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L120-L130) - this allows nodes launched by Karpenter to join the cluster
3. [An IAM role for service accounts mapped to the Karpenter controller via annotation](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L192-L193). This role needs the appropriate permissions to manage only the resources it is responsible for - for the given cluster. The key point here is the tagging requirement to scope access (which I suspect those in this thread are probably missing). [This tag](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L242-L243) maps to [this permission](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/modules/karpenter/main.tf#L98-L100) which is the associated permission that is claimed to be missing in this issue
4. A [security group for Karpenter](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L240-L241) to use when launching nodes - again, this can use [auto discovery with tags](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L145-L150) or you can explicitly tell Karpenter which security group to use
5. An [instance profile](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/examples/karpenter/main.tf#L198) for Karpenter to use on the nodes launched - again, IAM role needs to have RBAC access to allow nodes to join the cluster

**Comment by disparo13** [comment] 2023-05-12 21:32
@bryantbiggs Meanwhile, I opened a case with AWS Premium Support, asking them to analyze the policy documents I created with the module. Here's their answer:

_I have review the policy attached to the case, I have some observation that should explain why the policy isn’t working._

```
   {
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
```
_This policy has Resource as “*” and ResourceTag as condition key. However, if you review the documentation_ “[https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html” ](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html) _the structure is not supported for Action "ec2:TerminateInstances" and "ec2:DeleteLaunchTemplate"._

_As per the documentation, when you use the above Action and a wild card “*” for resource, you shouldn’t use ResourceTag for condition key._

_Next statement seems fine and conform to documentation_
```
Action: "ec2:RunInstances":
{
            "Action": "ec2:RunInstances",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:111111111111:launch-template/*",
            "Sid": ""
        },
```

_RunInstances is not supported for resource type spot-instance-request, this again - can be confirmed in documentation_ [https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html)

```
    {
            "Action": "ec2:RunInstances",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:111111111111:volume/*",
                "arn:aws:ec2:*:111111111111:subnet/*",
                "arn:aws:ec2:*:111111111111:spot-instances-request/*", ----- > This resource type is not supported for the Action "ec2:RunInstances"
                "arn:aws:ec2:*:111111111111:security-group/*",
                "arn:aws:ec2:*:111111111111:network-interface/*",
                "arn:aws:ec2:*:111111111111:instance/*"
            ],
            "Sid": ""
        },
```

**Comment by kjamieson-xilis** [comment] 2023-05-12 23:12
> RunInstances is not supported for resource type spot-instance-request, this again - can be confirmed in documentation

Ah - this applies to my situation, I created a provisioner for spot and that was where I received the error. I've got the example cluster up now and will create a spot provisioner to see if I can reproduce it.

**Comment by bryantbiggs** [comment] 2023-05-12 23:15
oh my goodness - on one hand I appreciate the additional details and insight, but on the other - still no reproduction

at least now I can infer one additional piece of information - I believe you are running spot instances; however, a reproduction would be more definitive

**Comment by kjamieson-xilis** [comment] 2023-05-12 23:31
Apologies if this is cluttering the discussion - I submitted a PR with the deployment I created, the region change to the example, and the error logs that result. I didn't realize that the example provisioner was actually deploying on spot, so I didn't need to create a new provisioner.

**Comment by kjamieson-xilis** [comment] 2023-05-13 00:21
Another apology - the PR above shows the error that occurs when you don't have the trust linked role created as detailed in the Getting Started guide; I've created that, and now the node does indeed launch and the pod runs successfully. I'll close that PR, and figure out the difference between this and my other setup.

**Comment by disparo13** [comment] 2023-05-15 07:15
@bryantbiggs I tried with spot and on-demand instance types, failing with the same error.

**Comment by bryantbiggs** [comment] 2023-05-15 12:26
> I tried with spot and on-demand instance types, failing with the same error.

using the code you provided, I am unable to reproduce the error

**Comment by bryantbiggs** [comment] 2023-05-17 13:07
closing for now until a proper reproduction can be provided to triage

**Comment by disparo13** [comment] 2023-05-17 13:07
@bryantbiggs 
> we have an example that demonstrates a working Karpenter implementation here

When did you run that example for the last time btw? According to it, it's using version 0.21.1 which is from Dec 29, 2022.

**Closed by bryantbiggs** 2023-05-17 13:07 UTC

**Comment by kjamieson-xilis** [comment] 2023-05-17 17:09
To close the loop on this - I've been able to resolve my permissions problems. I'm using launch templates because Node Templates do not support setting the ssh keypair (see https://github.com/aws/karpenter/issues/2432 for context). 

Under the policies block I've added a policy document that specifies RunInstances* on my aws_launch_template ARN as well as key-pair/* - I'm now able to launch spot instances successfully.  

I realize that launch templates are going to be deprecated, but I know there are other people that require being able to set the ssh keypair, so maybe not a documentation update but at least this info can be on this issue for people that search for it.

@bryantbiggs Thanks for your patience - I'm in the process of upgrading from Karpenter 0.6.4, so having to relearn a lot of the plumbing that I haven't looked at in over a year. Karpenter is so much better than dealing with ASGs that I had to deal with previously!

**Comment by bryantbiggs** [comment] 2023-05-19 11:21
Launch template support in Karpenter is deprecated

**Comment by benriou** [comment] 2023-06-01 13:07
I have been facing a similar same issue than @disparo13.
The instances created by Karpenter are **NOT tagged**  with `"ec2:ResourceTag/karpenter.sh/discovery"` by default.

As a proof, here is a screenshot of tags for an instantiated EC2 host by Karpenter

<img width="855" alt="CleanShot 2023-06-01 at 14 31 32@2x" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/40180297/b67e39ac-9781-4be2-ac0f-1cd4c415616b">

However this is expected by default by the Terraform EKS Karpenter Module [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/karpenter/main.tf#L114).

This can be fixed by adding a tag in the provisioner configuration.

It's working correctly after adding the corresponding tag (expected match condition by the Terraform EKS Karpenter Module) to the Provisioner configuration.

**Comment by igoratencompass** [comment] 2023-06-09 04:24
I'm using karpenter v0.27.5 and the controller does not start properly due to the error
```
2023-06-08T04:13:19.620Z	ERROR	controller	failed to delete launch template, UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: wk...
```
The missing `ec2:DeleteLaunchTemplate` in the karpenter policy is definitely an issue.
