### ISSUE TITLE
Wait for cluster to fully come up

### ISSUE THREAD

**Issue by IvanBoyko** [terraform-aws-modules/terraform-aws-eks#435] opened 2019-07-15 19:41 UTC
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Cluster is created, but all the system pods are still not started, specifically:
* coredns
* aws-node

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
terraform apply
kubectl get all -A
```

## What's the expected behavior?

Add an option to wait for system pods to fully come up before returning of `terraform apply`

**Comment by max-rocket-internet** [comment] 2019-07-16 10:04
We already have an issue for this I think: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/420

Can you try the resolution detailed here? https://github.com/terraform-aws-modules/terraform-aws-eks/issues/420#issuecomment-510956819

**Comment by max-rocket-internet** [comment] 2019-07-30 14:11
The 3 examples in [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples) all work when I test them. So could you please compare what you have with what is there and try to narrow down the cause? Specifically check:

- Are you disabling or changing anything related to DNS in your VPC?
- Are your work nodes in subnets that can reach the internet or your EKS API endpoint?

**Comment by mattsawyer77** [comment] 2019-08-09 16:46
I'm having this issue too (and I think it's different than the joining issue mentioned above #420). In my code I'm also using the kubernetes provider to create the aws-auth ConfigMap. Even with `depends_on` pointing to the aws_eks_cluster resource, it still tries to create the configmap before the kubernetes API server is available. If I wait a few minutes and then try again, it applies fine. If the aws_eks_cluster resource could wait until the kubernetes API server is up and available, it'd be ideal.

**Comment by mattsawyer77** [comment] 2019-08-20 19:16
update: I found I don't actually have an issue. I was using `data "aws_eks_cluster_auth"` to retrieve the token from the EKS cluster which resulted in a 401 error because it executed before the EKS clsuter was created. I placed a `depends_on` in that data block and it solved my issue.

**Comment by mattsawyer77** [comment] 2019-10-30 00:07
another update: though the message above works OK for creating the ConfigMap that causes the worker nodes to join the cluster, the joining operation seems to take some time. I also have some kubernetes provider resources that try to create but those seem to fail, ostensibly because the workers on which the resources would be running are not ready. 

Is there any way to wait for the whole cluster to become ready? @max-rocket-internet any ideas?

As a last resort I may drop into a local-exec provisioner to run some shell script that queries the cluster, but I'd really like to avoid that.

**Comment by max-rocket-internet** [comment] 2019-10-30 11:20
I'm gonna close this issue as it's old and we have an FAQ for nodes not joining the cluster: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-nodes-not-being-registered

> Is there any way to wait for the whole cluster to become ready?

I think the current version doesn't have this old problem?

> In my code I'm also using the kubernetes provider to create the aws-auth ConfigMap

Then you are not using a released version of this module I think.

**Closed by max-rocket-internet** 2019-10-30 11:20 UTC

**Comment by mattsawyer77** [comment] 2019-10-30 16:32
my bad! I realized I meant to open an issue with Terraform proper (I'm not actually using this terraform module). Nonetheless, I may take inspiration from it. Thanks and sorry for the noise.
