### ISSUE TITLE
Add assertions to help save lots of wasted time with known bad configurations.

### ISSUE THREAD

**Issue by brianbraunstein** [terraform-aws-modules/terraform-aws-eks#2861] opened 2023-12-28 20:11 UTC
## Is your request related to a new offering from AWS?
irrelevant

## Is your request related to a problem? Please describe.

The combination of the following things causes people to waste a lot of time while trying to get these modules working:
- It's very easy to configure these modules in a non-functional way that is known to be non-functional to experts.
- The main documentation sources (variable docs and examples) often don't provide enough information to know when you're doing something wrong.
- Trying to troubleshoot can take an enormous amount of time.  A 1 line fix could take ~half an hour to do 1 cycle of `try a fix->apply->wait 10+ mins->destroy->wait 10+ mins`.

Some examples:
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1972#issuecomment-1086239416 
  - Note the mention of this taking "2 weeks" so far for that person.  also note several other people running into the problem, and note that the solution was a single missing line which several experts weren't able to see right away.
- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.21.0/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-
  - Note that the variable docs and examples don't mention the mutually exclusive nature of these settings.  This is not an exceptional case.
- `use_custom_launch_template = false` will cause most security group variables on both the eks and the node group modules to be silently ignored.  Making the user's root module look very misleading.

### Add assertions to catch obviously incorrect usage.

For example, for https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.21.0/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername- check that only 1 of the two is set.  It would probably also allow deleting the FAQ entry then because the question will probably no longer come up at all.

There's probably an overwhelming number of assertions one could add, but at least adding the ones for common issues would already save a LOT of time.  If there's an issue filed, or an FAQ entry, those are clearly good candidates.

### When transparent assertions aren't possible...

For https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1972, it's more challenging to implement the assertion because you have to check across resources.  `module.eks.cluster_ip_family` needs to correspond with `module.vpc_cni_irsa.vpc_cni_enable_ipv(4|6)`.  I don't think there's any way to *transparently* add assertions to cases like this.

#### Option 1: change the module structure
Imagine a different approach to the IRSA module where the usage would look like:
```
module "irsa_vpc_cni" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks2/vpc-cni"
  eks = module.eks
}
```

Passing the full `module.eks` in would then allow running the necessary checks.

##### Side note
This approach would also avoid users having to do any of this stuff
```
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv6   = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-node"]
    }
  }
```
because this would already be baked in to the VPC CNI specific IRSA module (and similarly for other cases where there currently exists an `attach_*_policy` boolean.

#### Option 2: separate assert-only modules

I imagine there would be some objections to passing the entire `module.eks`.  I can see good arguments on both sides of that battle. If it's not desired, then the current module structure could be maintained, but also add new *assert-only* modules that might look like:
```
module "irsa_vpc_cni_check" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks/vpc-cni-check"
  eks = module.eks
  irsa = module.irsa_vpc_cni
}
```
(a very rough sketch of an idea, I'm not saying to design it to look exactly like this).

## Describe alternatives you've considered.

Completely rework the module design to follow the "make it hard to use wrong" principle so that assertions would be less necessary.  The `Option 1` above goes in this direction but it could be applied in a broader scope across all the modules.  (That's a much bigger discussion though, it could help a lot with this problem, but it probably doesn't make sense to discuss here).

## Additional context
none

**Comment by bryantbiggs** [comment] 2023-12-28 21:04
We would never create an argument that relies on an entire module output - that would be a very poor, fragile, and restrictive choice. I also don't agree with the assumption that assertions fix the issues linked. We cannot do anything within a module that alerts users to a missing provider implementation (first issue referenced). I do not see the validity nor the feasibility of this request

**Comment by bryantbiggs** [comment] 2024-01-02 21:59
> Do you know of any precedent for requiring version syncing of co-released submodules? It seems like a handy tool that could help libraries written in Terraform to solve problems with a more user friendly API. Modules are roughly equivalent to functions in other languages, with complex input and output structs. In other languages if you produce a library that has functions and complex structs, you wouldn't worry about passing pointers to those complex structs between different parts of the API.

Terraform is not like other software languages. You don't have abstractions - you can't put something behind an interface and have free will to change that. Nearly anything you do, its felt by users. If I change the shape of an input or output, theres nothing that can transform that or mask it, users experience that. Theres also nothing I can do to refactor a module without users feeling that (save for some of the newer features such as move blocks but those are still quite basic - you cannot use them on looping constructs). 

I'm not sure what the issue is thats trying to be solved here. Said differently - how would you prevent "bad configurations" with things like Ansible configurations or Kubernetes manifests?

**Comment by bryantbiggs** [comment] 2024-01-26 21:39
thank you! closing this one out for now, we'll continue to evaluate the functionality that the Terraform core provides for future improvements

**Closed by bryantbiggs** 2024-01-26 21:39 UTC
